#!/usr/bin/env python3
"""Generate exhaustive, surface-local JXP debug cleanup effects."""

from __future__ import annotations

import argparse
from pathlib import Path

from jxp_validation.core import ValidationContext
from jxp_validation.state_safety import (
    MAIN_DEBUG_ROOTS,
    MAP_DEBUG_ROOTS,
    PERSISTENT_CLEANUP_EXEMPTIONS,
    Surface,
    _scan_inventory,
)


MAIN_ROOT = Path(__file__).resolve().parents[2]
REPO_ROOT = MAIN_ROOT.parent
MAP_ROOT = REPO_ROOT / "japan_expanded_v2_map"
OUTPUT_NAME = "jxp_generated_debug_cleanup_effects.txt"


def _surface_names(inventory, label: str, kind: str) -> tuple[str, ...]:
    return tuple(
        sorted(
            name
            for name, occurrences in inventory.content_writes[kind].items()
            if (kind, name) not in PERSISTENT_CLEANUP_EXEMPTIONS
            and any(item.surface == label for item in occurrences)
        )
    )


def _render(inventory, label: str) -> str:
    effect = f"jxp_generated_{label}_debug_cleanup_effect"
    lines = [
        "# Generated by build_debug_cleanup_registry.py. Do not edit.",
        f"{effect} = {{",
    ]
    lines.extend(
        f"\tclr_country_flag = {name}"
        for name in _surface_names(inventory, label, "country_flag")
    )
    lines.extend(
        f"\tclr_global_flag = {name}"
        for name in _surface_names(inventory, label, "global_flag")
    )
    lines.extend(
        f"\tremove_country_modifier = {name}"
        for name in _surface_names(inventory, label, "country_modifier")
    )
    province_flags = _surface_names(inventory, label, "province_flag")
    province_modifiers = _surface_names(inventory, label, "province_modifier")
    if province_flags or province_modifiers:
        lines.append("\tevery_owned_province = {")
        lines.extend(f"\t\tclr_province_flag = {name}" for name in province_flags)
        lines.extend(
            f"\t\tremove_province_modifier = {name}"
            for name in province_modifiers
        )
        lines.append("\t}")
    lines.extend(("}", ""))
    return "\n".join(lines)


def build(*, check: bool) -> int:
    surfaces = (
        Surface("main", ValidationContext(MAIN_ROOT), MAIN_DEBUG_ROOTS),
        Surface("map", ValidationContext(MAP_ROOT), MAP_DEBUG_ROOTS),
    )
    inventory = _scan_inventory(surfaces)
    outputs = {
        MAIN_ROOT / "common/scripted_effects" / OUTPUT_NAME: _render(
            inventory, "main"
        ),
        MAP_ROOT / "common/scripted_effects" / OUTPUT_NAME: _render(
            inventory, "map"
        ),
    }
    drift = []
    for path, expected in outputs.items():
        if check:
            actual = path.read_text(encoding="utf-8") if path.is_file() else None
            if actual != expected:
                drift.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="")
        print(f"Created {path.relative_to(REPO_ROOT)}")
    if drift:
        for path in drift:
            print(f"DRIFT {path.relative_to(REPO_ROOT)}")
        return 1
    if check:
        print(f"PASS: {len(outputs)} generated debug cleanup registries are current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    return build(check=parser.parse_args().check)


if __name__ == "__main__":
    raise SystemExit(main())
