#!/usr/bin/env python3
"""Build the deterministic static oracle pack used by R12 runtime acceptance.

The pack deliberately separates facts that can be derived from checked-in
Clausewitz/map sources from facts that only the EU4 engine can demonstrate.
Run without ``--check`` to rebuild the committed JSON and with ``--check`` to
fail on byte-for-byte drift without writing anything.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import importlib.util
import io
import json
import re
import sys
from collections import defaultdict, deque
from datetime import date, timedelta
from pathlib import Path
from typing import Any, Iterable

import numpy as np
from PIL import Image


SCRIPT_PATH = Path(__file__).resolve()
SCRIPT_DIR = SCRIPT_PATH.parent
MOD_ROOT = SCRIPT_DIR.parents[1]
REPO_ROOT = MOD_ROOT.parent
BUILDER_DIR = MOD_ROOT / "tools" / "jxp_map_builder"
ASSET_DIR = MOD_ROOT / "tools" / "jxp_asset_builder"
DEFAULT_OUTPUT = SCRIPT_DIR / "generated" / "runtime_oracle_pack.json"
DATE_KEY = re.compile(r"^\d+\.\d+\.\d+$")
MISSION_METADATA = {"slot", "generic", "ai", "potential", "has_country_shield"}
SUBJECT_RELATIONSHIPS = {"vassal", "union", "dependency", "march"}
POSITION_NAMES = (
    "city",
    "unit",
    "province_text",
    "port",
    "manufactory",
    "combat",
    "trade_route",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", type=Path, required=True)
    parser.add_argument("--main-mod", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare the generated bytes with --output and do not write",
    )
    return parser.parse_args()


def canonical_json(value: Any, *, pretty: bool = False) -> bytes:
    if pretty:
        text = json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True)
    else:
        text = json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    return (text + ("\n" if pretty else "")).encode("utf-8")


def object_sha256(value: Any) -> str:
    return hashlib.sha256(canonical_json(value)).hexdigest()


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


class SourceTracker:
    """Read sources and retain a stable, complete SHA-256 provenance map."""

    def __init__(self, game_root: Path, main_mod: Path):
        self.game_root = game_root.resolve()
        self.main_mod = main_mod.resolve()
        self.roots = (
            ("map", MOD_ROOT.resolve()),
            ("main", self.main_mod),
            ("game", self.game_root),
            ("repo", REPO_ROOT.resolve()),
        )
        self.hashes: dict[str, str] = {}

    def key(self, path: Path) -> str:
        resolved = path.resolve()
        for label, root in self.roots:
            try:
                relative = resolved.relative_to(root)
            except ValueError:
                continue
            return f"{label}:{relative.as_posix()}"
        raise RuntimeError(f"Source lies outside all pinned roots: {resolved}")

    def pin(self, path: Path) -> str:
        path = path.resolve()
        if not path.is_file():
            raise FileNotFoundError(path)
        key = self.key(path)
        digest = file_sha256(path)
        previous = self.hashes.get(key)
        if previous is not None and previous != digest:
            raise RuntimeError(f"Source changed during oracle build: {key}")
        self.hashes[key] = digest
        return digest

    def bytes(self, path: Path) -> bytes:
        data = path.resolve().read_bytes()
        key = self.key(path)
        digest = hashlib.sha256(data).hexdigest()
        previous = self.hashes.get(key)
        if previous is not None and previous != digest:
            raise RuntimeError(f"Source changed during oracle build: {key}")
        self.hashes[key] = digest
        return data

    def text(self, path: Path, encoding: str | None = None) -> str:
        data = self.bytes(path)
        if encoding is not None:
            return data.decode(encoding)
        try:
            return data.decode("utf-8-sig")
        except UnicodeDecodeError:
            return data.decode("cp1252")

    def json(self, path: Path) -> Any:
        return json.loads(self.text(path, "utf-8-sig"))


def load_clausewitz_parser(tracker: SourceTracker, main_mod: Path):
    path = main_mod / "tools" / "jxp_validation" / "clausewitz.py"
    tracker.pin(path)
    spec = importlib.util.spec_from_file_location("jxp_runtime_oracle_clausewitz", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load Clausewitz parser: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def parse_cw(tracker: SourceTracker, cw, path: Path):
    return cw.parse_text(tracker.text(path), path).root


def scalar(cw, entry) -> str | None:
    return entry.value.text if isinstance(entry.value, cw.Scalar) else None


def ast_value(cw, value) -> Any:
    if isinstance(value, cw.Scalar):
        return {"quoted": bool(value.quoted), "scalar": value.text}
    return [
        {
            "key": entry.key,
            "operator": entry.operator,
            "value": ast_value(cw, entry.value),
        }
        for entry in value.entries
    ]


def ast_object(cw, obj, *, exclude: Iterable[str] = ()) -> list[dict[str, Any]]:
    omitted = set(exclude)
    return [
        {
            "key": entry.key,
            "operator": entry.operator,
            "value": ast_value(cw, entry.value),
        }
        for entry in obj.entries
        if entry.key not in omitted
    ]


def date_tuple(text: str) -> tuple[int, int, int]:
    values = tuple(int(part) for part in text.split("."))
    if len(values) != 3:
        raise ValueError(f"Invalid EU4 date: {text}")
    return values  # type: ignore[return-value]


def date_value(text: str) -> date:
    return date(*date_tuple(text))


def date_text(value: date) -> str:
    return f"{value.year}.{value.month}.{value.day}"


def case_date_token(text: str) -> str:
    year, month, day = date_tuple(text)
    return f"{year:04d}_{month:02d}_{day:02d}"


def find_r12(matrix: dict[str, Any]) -> dict[str, Any]:
    matches = [item for item in matrix.get("scenarios", []) if item.get("id") == "R12"]
    if len(matches) != 1:
        raise RuntimeError(f"Expected exactly one R12 scenario, found {len(matches)}")
    checklist = matches[0].get("executable_checklist")
    if not isinstance(checklist, dict):
        raise RuntimeError("R12 lacks executable_checklist")
    return checklist


def read_definition(tracker: SourceTracker, path: Path) -> tuple[dict[int, tuple[int, int, int]], dict[int, str]]:
    colors: dict[int, tuple[int, int, int]] = {}
    names: dict[int, str] = {}
    text = tracker.text(path, "cp1252")
    for row in csv.reader(io.StringIO(text), delimiter=";"):
        if not row or not row[0].strip().isdigit():
            continue
        pid = int(row[0])
        colors[pid] = tuple(int(value) for value in row[1:4])  # type: ignore[assignment]
        names[pid] = row[4] if len(row) > 4 else str(pid)
    return colors, names


def bitmap_ids(path: Path, colors: dict[int, tuple[int, int, int]], tracker: SourceTracker) -> np.ndarray:
    tracker.pin(path)
    rgb = np.asarray(Image.open(path).convert("RGB"), dtype=np.uint32)
    packed = (rgb[:, :, 0] << 16) | (rgb[:, :, 1] << 8) | rgb[:, :, 2]
    lookup = np.full(1 << 24, -1, dtype=np.int32)
    for pid, color in colors.items():
        lookup[(color[0] << 16) | (color[1] << 8) | color[2]] = pid
    ids = lookup[packed]
    if np.any(ids < 0):
        raise RuntimeError("provinces.bmp contains colors absent from definition.csv")
    return ids


def component_sizes(ids: np.ndarray, pid: int) -> list[int]:
    ys, xs = np.where(ids == pid)
    if not len(ys):
        return []
    y0, y1 = int(ys.min()), int(ys.max()) + 1
    x0, x1 = int(xs.min()), int(xs.max()) + 1
    mask = ids[y0:y1, x0:x1] == pid
    visited = np.zeros(mask.shape, dtype=bool)
    sizes: list[int] = []
    for y, x in zip(*np.where(mask)):
        if visited[y, x]:
            continue
        queue = deque([(int(y), int(x))])
        visited[y, x] = True
        size = 0
        while queue:
            cy, cx = queue.popleft()
            size += 1
            for ny, nx in ((cy - 1, cx), (cy + 1, cx), (cy, cx - 1), (cy, cx + 1)):
                if (
                    0 <= ny < mask.shape[0]
                    and 0 <= nx < mask.shape[1]
                    and mask[ny, nx]
                    and not visited[ny, nx]
                ):
                    visited[ny, nx] = True
                    queue.append((ny, nx))
        sizes.append(size)
    return sorted(sizes, reverse=True)


def extract_top_block(text: str, key: str) -> str | None:
    match = re.search(rf"(?m)^\s*{re.escape(key)}\s*=\s*\{{", text)
    if match is None:
        return None
    cursor = match.end() - 1
    depth = 0
    quoted = False
    escaped = False
    while cursor < len(text):
        char = text[cursor]
        if escaped:
            escaped = False
        elif char == "\\" and quoted:
            escaped = True
        elif char == '"':
            quoted = not quoted
        elif not quoted and char == "#":
            newline = text.find("\n", cursor)
            cursor = len(text) if newline < 0 else newline
            continue
        elif not quoted and char == "{":
            depth += 1
        elif not quoted and char == "}":
            depth -= 1
            if depth == 0:
                return text[match.start() : cursor + 1]
        cursor += 1
    return None


def parse_positions(text: str) -> dict[int, list[tuple[float, float]]]:
    positions: dict[int, list[tuple[float, float]]] = {}
    for match in re.finditer(r"(?m)^\s*(\d+)\s*=\s*\{", text):
        pid = int(match.group(1))
        block = extract_top_block(text[match.start() :], str(pid))
        if block is None:
            continue
        values_match = re.search(r"position\s*=\s*\{([^}]*)\}", block, flags=re.S)
        if values_match is None:
            continue
        values = [float(value) for value in re.findall(r"-?\d+(?:\.\d+)?", values_match.group(1))]
        positions[pid] = list(zip(values[0::2], values[1::2]))
    return positions


def parse_sea_ids(default_text: str) -> set[int]:
    match = re.search(r"sea_starts\s*=\s*\{([^}]*)\}", default_text, flags=re.S)
    if match is None:
        raise RuntimeError("default.map lacks sea_starts")
    return {int(value) for value in re.findall(r"\b\d+\b", match.group(1))}


def build_neighbor_sets(ids: np.ndarray, expected: set[int], sea_ids: set[int]) -> dict[int, set[int]]:
    neighbors: dict[int, set[int]] = defaultdict(set)
    for first, second in ((ids[:, :-1], ids[:, 1:]), (ids[:-1, :], ids[1:, :])):
        mask = (first != second) & (np.isin(first, list(expected)) | np.isin(second, list(expected)))
        for left, right in zip(first[mask].tolist(), second[mask].tolist()):
            a, b = int(left), int(right)
            if a in expected and b >= 0 and b not in sea_ids:
                neighbors[a].add(b)
            if b in expected and a >= 0 and a not in sea_ids:
                neighbors[b].add(a)
    return neighbors


def build_province_rows(
    tracker: SourceTracker,
    plan: dict[str, Any],
    manifest: dict[str, Any],
    compatibility: dict[str, Any],
) -> tuple[list[dict[str, Any]], dict[int, list[str]]]:
    definition_path = MOD_ROOT / "map" / "definition.csv"
    colors, names = read_definition(tracker, definition_path)
    ids = bitmap_ids(MOD_ROOT / "map" / "provinces.bmp", colors, tracker)
    expected = set(int(value) for value in plan["existing_japan_ids"])
    expected.update(int(item["id"]) for item in plan["new_provinces"])
    if len(expected) != 88:
        raise RuntimeError(f"Province plan contains {len(expected)} IDs, expected 88")

    default_text = tracker.text(MOD_ROOT / "map" / "default.map", "cp1252")
    sea_ids = parse_sea_ids(default_text)
    position_text = tracker.text(MOD_ROOT / "map" / "positions.txt", "cp1252")
    positions = parse_positions(position_text)
    adjacency_text = tracker.text(MOD_ROOT / "map" / "adjacencies.csv", "cp1252")
    adjacency_rows = list(csv.DictReader(io.StringIO(adjacency_text), delimiter=";"))
    tracker.pin(MOD_ROOT / "map" / "area.txt")
    tracker.pin(MOD_ROOT / "map" / "region.txt")

    areas: dict[int, str] = {}
    for area_name, provinces in plan["areas"].items():
        for pid in provinces:
            pid = int(pid)
            if pid in areas:
                raise RuntimeError(f"Province {pid} appears in two planned areas")
            areas[pid] = area_name
    if set(areas) != expected:
        raise RuntimeError("Planned area membership does not cover exactly 88 provinces")

    semantic_flags: dict[int, list[str]] = defaultdict(list)
    for flag, area_names in compatibility["geography_flags"].items():
        area_set = set(area_names)
        for pid in expected:
            if areas[pid] in area_set:
                semantic_flags[pid].append(flag)
    for flag, province_ids in compatibility["geography_province_flags"].items():
        for pid in province_ids:
            semantic_flags[int(pid)].append(flag)

    straits_by_province: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for planned in plan["straits"]:
        a, b = int(planned["from"]), int(planned["to"])
        matches = [
            row
            for row in adjacency_rows
            if {int(row["From"]), int(row["To"])} == {a, b}
            and row["Type"] == "sea"
            and row["Comment"] == planned["comment"]
        ]
        if len(matches) != 1:
            raise RuntimeError(f"Planned strait {a}<->{b} has {len(matches)} exact rows")
        row = matches[0]
        oracle = {
            "comment": row["Comment"],
            "from": int(row["From"]),
            "start": [int(row["start_x"]), int(row["start_y"])],
            "stop": [int(row["stop_x"]), int(row["stop_y"])],
            "through": int(row["Through"]),
            "to": int(row["To"]),
            "type": row["Type"],
        }
        straits_by_province[a].append(oracle)
        straits_by_province[b].append(oracle)

    neighbors = build_neighbor_sets(ids, expected, sea_ids)
    new_parent = {int(key): int(value) for key, value in plan["new_id_parent"].items()}
    strict_position_ids = set(int(value) for value in plan["editable_old_ids"]) | set(new_parent)
    manifest_counts = {int(key): int(value) for key, value in manifest["province_pixel_counts"].items()}
    if set(manifest_counts) != expected:
        raise RuntimeError("generated_manifest province_pixel_counts does not cover the 88 IDs")

    rows: list[dict[str, Any]] = []
    for pid in sorted(expected):
        pairs = positions.get(pid)
        if pairs is None or len(pairs) < 7:
            raise RuntimeError(f"Province {pid} lacks seven position coordinate pairs")
        pixel_count = int(np.count_nonzero(ids == pid))
        if pixel_count != manifest_counts[pid]:
            raise RuntimeError(f"Province {pid} pixel count drift: {pixel_count} != {manifest_counts[pid]}")
        port_x, port_y_bottom = pairs[3]
        if port_x == 0 and port_y_bottom == 0:
            port = {"present": False, "sea_province": None}
        else:
            x = int(round(port_x))
            y = ids.shape[0] - int(round(port_y_bottom))
            if not (0 <= x < ids.shape[1] and 0 <= y < ids.shape[0]):
                raise RuntimeError(f"Province {pid} port coordinate lies outside bitmap")
            sampled_pid = int(ids[y, x])
            points_to_sea = sampled_pid in sea_ids
            if not points_to_sea and pid in strict_position_ids:
                raise RuntimeError(f"Province {pid} port points to non-sea province {sampled_pid}")
            nearby = ids[max(0, y - 2) : y + 3, max(0, x - 2) : x + 3]
            if not np.any(nearby == pid) and pid in strict_position_ids:
                raise RuntimeError(f"Province {pid} port is not adjacent to its land pixels")
            port = {
                "bitmap_coordinate": [x, y],
                "coordinate_bottom_origin": [port_x, port_y_bottom],
                "present": True,
                "points_to_sea": points_to_sea,
                "sampled_province": sampled_pid,
                "sea_province": sampled_pid if points_to_sea else None,
                "static_validation_scope": (
                    "strict_companion_position_gate"
                    if pid in strict_position_ids
                    else "inherited_unedited_vanilla_position"
                ),
            }
        components = component_sizes(ids, pid)
        row = {
            "area": areas[pid],
            "component_sizes": components,
            "id": pid,
            "land_neighbors": sorted(neighbors.get(pid, set())),
            "name": names[pid],
            "pixel_count": pixel_count,
            "port": port,
            "position_pairs": {
                name: [float(pairs[index][0]), float(pairs[index][1])]
                for index, name in enumerate(POSITION_NAMES)
            },
            "semantic_flags": sorted(semantic_flags.get(pid, [])),
            "source_kind": "new" if pid in new_parent else "existing",
            "source_parent": new_parent.get(pid),
            "straits": sorted(straits_by_province.get(pid, []), key=lambda item: (item["from"], item["to"])),
            "runtime_observation_only": [
                "rendered province shape, colour, border, and click target",
                "rendered label readability and overlap",
                "rendered city/unit/manufactory/port model placement",
                "rendered strait and port directionality",
            ],
        }
        rows.append(row)
    return rows, {pid: sorted(values) for pid, values in semantic_flags.items()}


def dated_entries(cw, root) -> list[tuple[tuple[int, int, int], Any]]:
    result = []
    for entry in root.entries:
        if entry.key and DATE_KEY.fullmatch(entry.key) and isinstance(entry.value, cw.Object):
            result.append((date_tuple(entry.key), entry.value))
    return sorted(result, key=lambda item: item[0])


def apply_history_entries(cw, obj, state: dict[str, Any]) -> None:
    for _path, entry in cw.walk_entries(obj):
        value = scalar(cw, entry)
        if value is None:
            continue
        if entry.key in {"owner", "controller"}:
            state[entry.key] = value
        elif entry.key == "add_core":
            state["cores"].add(value)
        elif entry.key == "remove_core":
            state["cores"].discard(value)


def province_history_at(cw, root, when: tuple[int, int, int]) -> dict[str, Any]:
    state: dict[str, Any] = {"controller": None, "cores": set(), "owner": None}
    root_only = cw.Object(tuple(entry for entry in root.entries if not (entry.key and DATE_KEY.fullmatch(entry.key))))
    apply_history_entries(cw, root_only, state)
    for changed, block in dated_entries(cw, root):
        if changed > when:
            break
        apply_history_entries(cw, block, state)
    if state["owner"] is None:
        raise RuntimeError("Province history state lacks owner")
    return {
        "controller": state["controller"],
        "cores": sorted(state["cores"]),
        "owner": state["owner"],
    }


def effective_history_file(roots: tuple[Path, ...], directory: str, pattern: str) -> Path | None:
    for root in roots:
        matches = sorted((root / directory).glob(pattern)) if (root / directory).is_dir() else []
        if len(matches) > 1:
            raise RuntimeError(f"Ambiguous effective history source for {pattern}: {matches}")
        if matches:
            return matches[0]
    return None


def capital_at(cw, root, when: tuple[int, int, int]) -> int | None:
    current: int | None = None
    for entry in root.entries:
        if entry.key == "capital" and isinstance(entry.value, cw.Scalar):
            current = int(entry.value.text)
    for changed, block in dated_entries(cw, root):
        if changed > when:
            break
        for _path, entry in cw.walk_entries(block):
            if entry.key == "capital" and isinstance(entry.value, cw.Scalar):
                current = int(entry.value.text)
    return current


def effective_diplomacy_files(game_root: Path, main_mod: Path) -> list[Path]:
    effective: dict[str, Path] = {}
    for root in (game_root, main_mod, MOD_ROOT):
        directory = root / "history" / "diplomacy"
        if not directory.is_dir():
            continue
        for path in sorted(directory.glob("*.txt")):
            effective[path.name.casefold()] = path
    return sorted(effective.values(), key=lambda value: value.name.casefold())


def parse_subject_intervals(tracker: SourceTracker, cw, game_root: Path, main_mod: Path) -> list[dict[str, Any]]:
    intervals: list[dict[str, Any]] = []
    for path in effective_diplomacy_files(game_root, main_mod):
        root = parse_cw(tracker, cw, path)
        for entry in root.entries:
            if entry.key not in SUBJECT_RELATIONSHIPS or not isinstance(entry.value, cw.Object):
                continue
            first = cw.first_scalar(entry.value, "first")
            second = cw.first_scalar(entry.value, "second")
            start = cw.first_scalar(entry.value, "start_date")
            end = cw.first_scalar(entry.value, "end_date")
            if not first or not second or not start:
                continue
            subject_type = cw.first_scalar(entry.value, "subject_type")
            intervals.append(
                {
                    "end_exclusive": end,
                    "overlord": first,
                    "relationship": subject_type or entry.key,
                    "source": tracker.key(path),
                    "start_inclusive": start,
                    "subject": second,
                }
            )
    return intervals


def relationship_active(item: dict[str, Any], when: tuple[int, int, int]) -> bool:
    if date_tuple(item["start_inclusive"]) > when:
        return False
    end = item.get("end_exclusive")
    return end is None or when < date_tuple(end)


def build_history_states(
    tracker: SourceTracker,
    cw,
    game_root: Path,
    main_mod: Path,
    province_ids: list[int],
    history_plan: dict[str, Any],
    checklist: dict[str, Any],
) -> list[dict[str, Any]]:
    province_histories: dict[int, Any] = {}
    for pid in province_ids:
        matches = sorted((MOD_ROOT / "history" / "provinces").glob(f"{pid} - *.txt"))
        if len(matches) != 1:
            raise RuntimeError(f"Province {pid} has {len(matches)} companion history files")
        province_histories[pid] = parse_cw(tracker, cw, matches[0])

    requested: list[tuple[str, str, dict[str, Any]]] = []
    bookmarks = checklist["official_bookmark_dates"]
    if bookmarks != history_plan["bookmark_dates"]:
        raise RuntimeError("R12 bookmark dates drifted from history_plan")
    for text in bookmarks:
        requested.append((f"r12_bookmark_{case_date_token(text)}", text, {"sample_kind": "bookmark"}))
    for boundary in checklist["history_boundary_dates"]:
        exact = date_value(boundary)
        for suffix, sampled in (("prev", exact - timedelta(days=1)), ("exact", exact), ("next", exact + timedelta(days=1))):
            text = date_text(sampled)
            requested.append(
                (
                    f"r12_boundary_{case_date_token(boundary)}_{suffix}",
                    text,
                    {"boundary": boundary, "sample_kind": f"boundary_{suffix}"},
                )
            )
    for text in checklist["non_boundary_slider_samples"]:
        requested.append((f"r12_slider_{case_date_token(text)}", text, {"sample_kind": "non_boundary_slider"}))
    if len(requested) != 63:
        raise RuntimeError(f"History case matrix contains {len(requested)} cases, expected 63")

    raw_states: list[dict[str, Any]] = []
    owner_tags: set[str] = set()
    for case_id, text, metadata in requested:
        when = date_tuple(text)
        province_states = {
            str(pid): province_history_at(cw, province_histories[pid], when)
            for pid in province_ids
        }
        owners = {pid: state["owner"] for pid, state in province_states.items()}
        owner_tags.update(owners.values())
        raw_states.append(
            {
                "case_id": case_id,
                "date": text,
                **metadata,
                "province_states": province_states,
            }
        )

    country_roots: dict[str, Any] = {}
    country_sources: dict[str, str] = {}
    precedence = (MOD_ROOT, main_mod, game_root)
    for tag in sorted(owner_tags):
        path = effective_history_file(precedence, "history/countries", f"{tag} - *.txt")
        if path is None:
            raise RuntimeError(f"Cannot resolve effective country history for landed owner {tag}")
        country_roots[tag] = parse_cw(tracker, cw, path)
        country_sources[tag] = tracker.key(path)

    subject_intervals = parse_subject_intervals(tracker, cw, game_root, main_mod)
    new_country_contract = {item["tag"]: item for item in history_plan["countries"]}
    result: list[dict[str, Any]] = []
    for raw in raw_states:
        when = date_tuple(raw["date"])
        holdings: dict[str, list[int]] = defaultdict(list)
        for pid, state in raw["province_states"].items():
            holdings[state["owner"]].append(int(pid))
        countries = []
        for tag in sorted(holdings):
            subjects = [
                {
                    "overlord": item["overlord"],
                    "relationship": item["relationship"],
                }
                for item in subject_intervals
                if item["subject"] == tag and relationship_active(item, when)
            ]
            subjects.sort(key=lambda item: (item["overlord"], item["relationship"]))
            capital = capital_at(cw, country_roots[tag], when)
            if capital is None:
                raise RuntimeError(f"{tag} has no capital at {raw['date']}")
            contract = new_country_contract.get(tag)
            if contract is not None and date_tuple(contract["start"]) <= when < date_tuple(contract["end"]):
                if capital not in holdings[tag]:
                    raise RuntimeError(f"{tag} capital {capital} is not held at {raw['date']}")
                if len(subjects) != 1:
                    raise RuntimeError(f"Landed companion tag {tag} has {len(subjects)} overlords at {raw['date']}")
            countries.append(
                {
                    "capital": capital,
                    "country_history_source": country_sources[tag],
                    "held_provinces": sorted(holdings[tag]),
                    "subject_relationships": subjects,
                    "tag": tag,
                }
            )
        state = {
            **raw,
            "landed_countries": countries,
            "runtime_observation_only": [
                "country/date-selection UI presentation and selectable-start availability",
                "engine materialisation of owner, core, capital, and subject state after loading",
            ],
        }
        state["state_sha256"] = object_sha256(state)
        result.append(state)
    return result


def parse_localisation(text: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for line in text.splitlines():
        match = re.match(r'^\s*([^\s:#]+):\d+\s+"(.*)"\s*$', line)
        if match:
            result[match.group(1)] = match.group(2)
    return result


def localisation_keys(text: str) -> set[str]:
    """Read keys even when EU4SpecialEscape bytes include control newlines."""

    return set(re.findall(r"(?m)^\s*([^\s:#]+):\d+\s+", text))


def event_index(cw, roots: Iterable[Any]) -> dict[str, tuple[Any, int]]:
    events: dict[str, tuple[Any, int]] = {}
    for root in roots:
        for entry in root.entries:
            if entry.key != "country_event" or not isinstance(entry.value, cw.Object):
                continue
            event_id = cw.first_scalar(entry.value, "id")
            if event_id:
                events[event_id] = (entry.value, entry.line)
    return events


def direct_objects(cw, obj, key: str) -> list[Any]:
    return [entry.value for entry in obj.entries if entry.key == key and isinstance(entry.value, cw.Object)]


def option_summary(cw, option) -> dict[str, Any]:
    flags_set: set[str] = set()
    flags_cleared: set[str] = set()
    modifiers_added: list[dict[str, Any]] = []
    modifiers_removed: set[str] = set()
    scripted_effects: set[str] = set()
    scalar_effects: list[dict[str, str]] = []
    target_rules: list[dict[str, Any]] = []
    seen_targets: set[tuple[Any, ...]] = set()
    for path, entry in cw.walk_entries(option):
        value = scalar(cw, entry)
        if entry.key == "set_country_flag" and value:
            flags_set.add(value)
        elif entry.key == "clr_country_flag" and value:
            flags_cleared.add(value)
        elif entry.key == "remove_country_modifier" and value:
            modifiers_removed.add(value)
        elif entry.key == "add_country_modifier" and isinstance(entry.value, cw.Object):
            modifiers_added.append(
                {
                    "duration": cw.first_scalar(entry.value, "duration"),
                    "name": cw.first_scalar(entry.value, "name"),
                }
            )
        if value is not None and entry.key and entry.key.startswith("jxp_") and value == "yes":
            scripted_effects.add(entry.key)
        if value is not None and entry.key and entry.key.startswith(("add_", "cede_")):
            scalar_effects.append({"effect": entry.key, "value": value})
        if entry.key and entry.key.isdigit() and isinstance(entry.value, cw.Object):
            key = ("province", int(entry.key), "if" in path or "else_if" in path)
            if key not in seen_targets:
                target_rules.append(
                    {
                        "conditional": bool(key[2]),
                        "province_id": int(entry.key),
                        "scope": "exact_province",
                    }
                )
                seen_targets.add(key)
        elif entry.key == "capital_scope" and isinstance(entry.value, cw.Object):
            key = ("capital",)
            if key not in seen_targets:
                target_rules.append({"scope": "dynamic", "selector": "$capital_at_pre_state"})
                seen_targets.add(key)
        elif entry.key == "random_owned_province" and isinstance(entry.value, cw.Object):
            key = ("random_owned",)
            if key not in seen_targets:
                target_rules.append(
                    {
                        "predicate": ast_object(cw, cw.first_object(entry.value, "limit") or entry.value),
                        "scope": "random_owned_province",
                    }
                )
                seen_targets.add(key)
    if not target_rules:
        target_rules.append({"scope": "event_country"})
    return {
        "country_flags_cleared": sorted(flags_cleared),
        "country_flags_set": sorted(flags_set),
        "country_modifiers_added": modifiers_added,
        "country_modifiers_removed": sorted(modifiers_removed),
        "scalar_effects": scalar_effects,
        "scripted_effects": sorted(scripted_effects),
        "target_rules": target_rules,
    }


def resolve_vanilla_event_art(
    tracker: SourceTracker,
    game_root: Path,
    picture: str,
    gfx_text: str,
) -> dict[str, Any]:
    pattern = re.compile(
        r"spriteType\s*=\s*\{(?:(?!spriteType\s*=).)*?"
        + r"name\s*=\s*\"?"
        + re.escape(picture)
        + r"\"?(?:(?!spriteType\s*=).)*?texturefile\s*=\s*\"([^\"]+)\"(?:(?!spriteType\s*=).)*?\}",
        flags=re.S,
    )
    match = pattern.search(gfx_text)
    if match is None:
        raise RuntimeError(f"Cannot resolve vanilla event picture {picture}")
    relative = match.group(1).replace("/", "\\")
    texture = game_root / Path(relative)
    digest = tracker.pin(texture)
    return {"file": tracker.key(texture), "sha256": digest, "sprite": picture}


def build_event_options(
    tracker: SourceTracker,
    cw,
    game_root: Path,
    main_mod: Path,
    checklist: dict[str, Any],
    asset_manifest: dict[str, Any],
) -> list[dict[str, Any]]:
    map_event_path = MOD_ROOT / "events" / "jxp_map_events.txt"
    main_event_path = main_mod / "events" / "jxp_77_regional_flavor_events.txt"
    roots = [parse_cw(tracker, cw, map_event_path), parse_cw(tracker, cw, main_event_path)]
    events = event_index(cw, roots)

    map_source_loc = MOD_ROOT / "localisation_source" / "jxp_map_content_l_english_utf8_source.yml"
    map_active_loc = MOD_ROOT / "localisation" / "jxp_map_content_l_english.yml"
    main_source_loc = main_mod / "localisation_source" / "jxp_77_regional_flavor_l_english_utf8_source.yml"
    main_active_loc = main_mod / "localisation" / "jxp_77_regional_flavor_l_english.yml"
    source_loc = {
        "jxp_map": parse_localisation(tracker.text(map_source_loc, "utf-8-sig")),
        "jxp_77": parse_localisation(tracker.text(main_source_loc, "utf-8-sig")),
    }
    active_keys = {
        "jxp_map": localisation_keys(tracker.text(map_active_loc, "utf-8-sig")),
        "jxp_77": localisation_keys(tracker.text(main_active_loc, "utf-8-sig")),
    }

    event_gfx_path = game_root / "interface" / "eventpictures.gfx"
    event_gfx_text = tracker.text(event_gfx_path, "cp1252")
    rows: list[dict[str, Any]] = []
    expected_options = checklist["visible_event_options"]
    if checklist["visible_event_ids"] != list(expected_options):
        raise RuntimeError("R12 visible_event_ids/options ordering drifted")
    for event_id in checklist["visible_event_ids"]:
        if event_id not in events:
            raise RuntimeError(f"Visible event {event_id} is absent from source")
        event, line = events[event_id]
        title = cw.first_scalar(event, "title")
        desc = cw.first_scalar(event, "desc")
        picture = cw.first_scalar(event, "picture")
        if not title or not desc or not picture:
            raise RuntimeError(f"Visible event {event_id} lacks title/desc/picture")
        namespace = event_id.split(".", 1)[0]
        if event_id.startswith("jxp_map."):
            asset = asset_manifest["events"].get(event_id)
            if asset is None:
                raise RuntimeError(f"Asset manifest lacks event art for {event_id}")
            texture = MOD_ROOT / Path(asset["file"].replace("\\", "/"))
            digest = tracker.pin(texture)
            if digest != asset["sha256"]:
                raise RuntimeError(f"Event art hash drift for {event_id}")
            art = {"file": tracker.key(texture), "sha256": digest, "sprite": picture}
            source_key = tracker.key(map_event_path)
        else:
            art = resolve_vanilla_event_art(tracker, game_root, picture, event_gfx_text)
            source_key = tracker.key(main_event_path)
        for key in (title, desc):
            if key not in source_loc[namespace] or key not in active_keys[namespace]:
                raise RuntimeError(f"Localisation key {key} is absent from source or active localisation")

        mtth = cw.first_object(event, "mean_time_to_happen")
        options = direct_objects(cw, event, "option")
        actual_names = [cw.first_scalar(option, "name") for option in options]
        if actual_names != expected_options[event_id]:
            raise RuntimeError(f"Event {event_id} option drift: {actual_names}")
        for option in options:
            option_name = cw.first_scalar(option, "name")
            assert option_name is not None
            if option_name not in source_loc[namespace] or option_name not in active_keys[namespace]:
                raise RuntimeError(f"Localisation key {option_name} is absent from source or active localisation")
            script = ast_object(cw, option, exclude={"name", "ai_chance"})
            runtime_only = [
                "rendered event picture, title, description, option text, and layout",
                "engine application of the scripted effects to the captured pre-state",
            ]
            if mtth is not None:
                runtime_only.append("exact mean-time-to-happen firing date and random roll")
            if event_id == "jxp_map.22" and option_name == "jxp_map.22.a":
                runtime_only.append("exact random owned port province selected by the engine")
            repeatability = "repeatable_no_op_diagnostic" if event_id == "jxp_map.900" else ""
            if event_id.startswith("jxp_77."):
                repeatability = "gated_by_mission_or_decision_cooldown; no one-time country flag"
            elif not repeatability:
                repeatability = "one_time_country_flag"
            row = {
                "art": art,
                "description_key": desc,
                "description_text": source_loc[namespace][desc],
                "effect_sha256": object_sha256(script),
                "event_id": event_id,
                "event_source": source_key,
                "event_source_line": line,
                "mean_time_to_happen": ast_object(cw, mtth) if mtth is not None else None,
                "option_key": option_name,
                "option_text": source_loc[namespace][option_name],
                "repeatability": repeatability,
                "runtime_observation_only": runtime_only,
                "script": script,
                "static_summary": option_summary(cw, option),
                "title_key": title,
                "title_text": source_loc[namespace][title],
            }
            if any(
                item["effect"] == "add_stability_or_adm_power"
                for item in row["static_summary"]["scalar_effects"]
            ):
                row["conditional_resolution"] = {
                    "if_stability_is_3": {"add_adm_power": 50},
                    "otherwise": {"add_stability": 1},
                }
            rows.append(row)
    if len(rows) != 37:
        raise RuntimeError(f"Generated {len(rows)} event option rows, expected 37")
    return rows


def mission_series_index(cw, root) -> dict[str, Any]:
    return {
        entry.key: entry.value
        for entry in root.entries
        if entry.key and isinstance(entry.value, cw.Object)
    }


def mission_objects(cw, series) -> dict[str, Any]:
    return {
        entry.key: entry.value
        for entry in series.entries
        if entry.key not in MISSION_METADATA and entry.key and isinstance(entry.value, cw.Object)
    }


def build_origin_profiles(
    tracker: SourceTracker,
    cw,
    main_mod: Path,
    checklist: dict[str, Any],
    compatibility: dict[str, Any],
    asset_manifest: dict[str, Any],
) -> list[dict[str, Any]]:
    mission_path = MOD_ROOT / "missions" / "jxp_map_new_daimyo_missions.txt"
    root = parse_cw(tracker, cw, mission_path)
    series_index = mission_series_index(cw, root)
    source_loc_path = MOD_ROOT / "localisation_source" / "jxp_map_content_l_english_utf8_source.yml"
    active_loc_path = MOD_ROOT / "localisation" / "jxp_map_content_l_english.yml"
    source_loc = parse_localisation(tracker.text(source_loc_path, "utf-8-sig"))
    active_keys = localisation_keys(tracker.text(active_loc_path, "utf-8-sig"))
    representatives = checklist["origin_profiles"]
    chains = checklist["origin_chain_missions"]
    legacy_names = {
        "warrior": "warrior",
        "court": "court",
        "maritime": "sea",
        "frontier": "frontier",
        "temple_market": "temple",
    }
    profiles: list[dict[str, Any]] = []
    all_mission_ids: list[str] = []
    for tag, series_name in representatives.items():
        categories = [name for name, group in compatibility["groups"].items() if tag in group["tags"]]
        if len(categories) != 1:
            raise RuntimeError(f"Representative {tag} belongs to {len(categories)} origin groups")
        category = categories[0]
        contract = compatibility["groups"][category]
        if contract["map_series"] != series_name:
            raise RuntimeError(f"R12 origin profile {tag} drifted from compatibility contract")
        series = series_index.get(series_name)
        if series is None:
            raise RuntimeError(f"Mission series {series_name} is absent")
        available = mission_objects(cw, series)
        expected_chain = chains[tag]
        if list(available) != expected_chain:
            raise RuntimeError(f"Mission order drift for {tag}: {list(available)}")
        missions = []
        for mission_id in expected_chain:
            mission = available[mission_id]
            icon = cw.first_scalar(mission, "icon")
            position = cw.first_scalar(mission, "position")
            required = [value.text for value in cw.bare_scalars(cw.first_object(mission, "required_missions"))]
            if not icon or position is None:
                raise RuntimeError(f"Mission {mission_id} lacks icon/position")
            asset = asset_manifest["missions"].get(icon)
            if asset is None:
                raise RuntimeError(f"Mission icon manifest lacks {icon}")
            texture = MOD_ROOT / Path(asset["file"].replace("\\", "/"))
            digest = tracker.pin(texture)
            if digest != asset["sha256"]:
                raise RuntimeError(f"Mission icon hash drift for {icon}")
            title_key, desc_key = f"{mission_id}_title", f"{mission_id}_desc"
            if title_key not in source_loc or desc_key not in source_loc:
                raise RuntimeError(f"Mission localisation missing for {mission_id}")
            if title_key not in active_keys or desc_key not in active_keys:
                raise RuntimeError(f"Active mission localisation missing for {mission_id}")
            trigger = cw.first_object(mission, "trigger")
            effect = cw.first_object(mission, "effect")
            effect_ast = ast_object(cw, effect) if effect is not None else []
            missions.append(
                {
                    "description_key": desc_key,
                    "description_text": source_loc[desc_key],
                    "effect": effect_ast,
                    "effect_sha256": object_sha256(effect_ast),
                    "icon": {
                        "file": tracker.key(texture),
                        "sha256": digest,
                        "sprite": icon,
                    },
                    "mission_id": mission_id,
                    "position": int(position),
                    "required_missions": required,
                    "runtime_observation_only": [
                        "mission button visibility, icon rendering, tooltip layout, and clickable completion",
                        "engine evaluation of mission trigger and application of mission effects",
                    ],
                    "title_key": title_key,
                    "title_text": source_loc[title_key],
                    "trigger": ast_object(cw, trigger) if trigger is not None else [],
                }
            )
            all_mission_ids.append(mission_id)
        other_series = sorted(
            group["map_series"]
            for name, group in compatibility["groups"].items()
            if name != category
        )
        legacy = f"jxp_map_{legacy_names[category]}_legacy"
        profiles.append(
            {
                "category": category,
                "expected_map_series": series_name,
                "forbidden_map_series": other_series,
                "group_tags": contract["tags"],
                "legacy_modifier": legacy,
                "main_origin_trigger": contract["main_origin_trigger"],
                "map_origin_trigger": contract["map_origin_trigger"],
                "missions": {item["mission_id"]: item for item in missions},
                "origin_flag": f"jxp_map_origin_{tag.lower()}",
                "representative_tag": tag,
                "runtime_observation_only": [
                    "exact mission-column exclusivity after engine mission-tree swap",
                    "unified tag/route chosen by the runtime fixture and the resulting rendered main mission tree",
                    "legacy modifier visibility and persistence after save/reload",
                ],
                "shared_main_series": compatibility["shared_main_series"],
                "unification_inheritance": {
                    "annual_event": "jxp_map.100",
                    "expected_permanent_modifier": legacy,
                    "expected_preserved_origin_flag": f"jxp_map_origin_{tag.lower()}",
                },
            }
        )
    if len(profiles) != 5 or len(all_mission_ids) != 33 or len(set(all_mission_ids)) != 33:
        raise RuntimeError(
            f"Origin pack has {len(profiles)} profiles/{len(all_mission_ids)} missions, expected 5/33"
        )
    return profiles


def top_object(cw, root, name: str):
    matches = [entry.value for entry in root.entries if entry.key == name and isinstance(entry.value, cw.Object)]
    if len(matches) != 1:
        raise RuntimeError(f"Expected one {name} object, found {len(matches)}")
    return matches[0]


def build_unification(
    tracker: SourceTracker,
    cw,
    main_mod: Path,
    province_rows: list[dict[str, Any]],
) -> dict[str, Any]:
    main_debug_path = main_mod / "common" / "scripted_effects" / "jxp_debug_effects.txt"
    main_effects_path = main_mod / "common" / "scripted_effects" / "jxp_scripted_effects.txt"
    refresh_event_path = main_mod / "events" / "jxp_23_mission_refresh_events.txt"
    map_effects_path = MOD_ROOT / "common" / "scripted_effects" / "jxp_map_effects.txt"
    map_events_path = MOD_ROOT / "events" / "jxp_map_events.txt"
    on_actions_path = MOD_ROOT / "common" / "on_actions" / "jxp_map_on_actions.txt"
    map_triggers_path = MOD_ROOT / "common" / "scripted_triggers" / "jxp_map_triggers.txt"
    debug_root = parse_cw(tracker, cw, main_debug_path)
    unify = top_object(cw, debug_root, "jxp_debug_unify_japan_effect")
    unify_ast = ast_object(cw, unify)
    for path in (main_effects_path, refresh_event_path, map_effects_path, map_events_path, on_actions_path, map_triggers_path):
        tracker.pin(path)

    province_oracles = {
        str(row["id"]): {
            "core_assertion": {"contains": ["$actor_tag"], "exclusive": False},
            "owner": "$actor_tag",
            "province_id": row["id"],
            "semantic_flags": row["semantic_flags"],
            "runtime_observation_only": [
                "illegal occupation/controller cleanup after cede_province",
                "rendered owner colour, border refresh, and province tooltip",
            ],
        }
        for row in province_rows
    }
    lifecycle_rows = [
        {
            "case_id": "r12_startup_geography_and_origin_initialization",
            "static_oracle": {
                "global_flags_set": ["jxp_map_geography_contract_v011", "jxp_map_geography_contract_v012"],
                "new_tag_flags": [
                    "jxp_map_initialized",
                    "jxp_map_identity_migration_v012",
                    "jxp_map_regional_flavor_migration_v013",
                    "jxp_map_runtime_migration_v011",
                ],
                "origin_cardinality": "exactly_one_for_companion_tag",
            },
            "runtime_observation_only": ["engine on_startup/on_country_released ordering and persisted flag state"],
        },
        {
            "case_id": "r12_unification_immediate_refresh",
            "static_oracle": {
                "mission_refresh_effect": "jxp_refresh_route_missions_effect",
                "pending_flag": "jxp_mission_refresh_pending",
                "scheduled_event": {"days": 1, "id": "jxp_mission_refresh.1"},
                "swap_non_generic_missions": True,
            },
            "runtime_observation_only": ["same-tick mission UI refresh and engine event scheduling"],
        },
        {
            "case_id": "r12_unification_day_one_refresh",
            "static_oracle": {
                "clears_pending_flag": "jxp_mission_refresh_pending",
                "event": "jxp_mission_refresh.1",
                "swap_non_generic_missions": True,
            },
            "runtime_observation_only": ["exact event execution date and resulting mission UI"],
        },
        {
            "case_id": "r12_post_tag_idea_sync",
            "static_oracle": {
                "event": "jxp_map.102",
                "mean_time_to_happen_days": 1,
                "sets_flag": "jxp_map_post_tag_idea_sync_v012",
                "sync_effect": "jxp_sync_route_national_ideas_effect",
            },
            "runtime_observation_only": ["exact mean-time-to-happen firing date and random roll", "rendered idea group after sync"],
        },
        {
            "case_id": "r12_first_applicable_annual_legacy",
            "static_oracle": {
                "event": "jxp_map.100",
                "one_time_flag": "jxp_map_legacy_granted",
                "outcome": "exactly one category legacy modifier with duration -1",
                "pulse": "on_yearly_pulse_5",
            },
            "runtime_observation_only": ["exact yearly-pulse execution date and event ordering"],
        },
        {
            "case_id": "r12_mission_repair_guard",
            "static_oracle": {
                "event": "jxp_map.101",
                "expected_firings_with_valid_mission_fingerprint": 0,
                "mean_time_to_happen_days": 90,
            },
            "runtime_observation_only": ["exact mean-time-to-happen firing date if the repair trigger becomes true"],
        },
        {
            "case_id": "r12_twelve_month_reload_stability",
            "static_oracle": {
                "duplicate_initialization": False,
                "duplicate_legacy_grants": False,
                "duplicate_one_time_content": False,
            },
            "runtime_observation_only": [
                "save serialization/reload persistence",
                "absence of duplicate initialization, scheduling, legacy grants, and one-time content across twelve elapsed months",
            ],
        },
    ]
    return {
        "actor_tag": "$actor_tag",
        "formation_profile": {
            "constraint": "runtime fixture must record a deterministic target tag and formation route",
            "target_tag": "$runtime_profile_target_tag",
            "runtime_observation_only": [
                "chosen unified target tag/formation route and tag-switch timing",
                "rendered post-formation national ideas and mission tree",
            ],
        },
        "lifecycle": {item["case_id"]: item for item in lifecycle_rows},
        "province_rows": province_oracles,
        "source_effect": {
            "ast": unify_ast,
            "sha256": object_sha256(unify_ast),
            "source": tracker.key(main_debug_path),
        },
        "static_country_effects": {
            "add_imperial_sanction": 10,
            "add_prestige": 25,
            "add_tenka_order": 10,
            "mission_refresh": "immediate plus scheduled next-day refresh",
        },
    }


def build_pack(game_root: Path, main_mod: Path) -> dict[str, Any]:
    game_root = game_root.resolve()
    main_mod = main_mod.resolve()
    tracker = SourceTracker(game_root, main_mod)
    tracker.pin(SCRIPT_PATH)
    tracker.pin(MOD_ROOT / "tools" / "validate_all.ps1")
    tracker.pin(SCRIPT_DIR / "validate_map.py")
    tracker.pin(SCRIPT_DIR / "validate_history.py")
    tracker.pin(SCRIPT_DIR / "validate_content.py")

    cw = load_clausewitz_parser(tracker, main_mod)
    plan = tracker.json(BUILDER_DIR / "province_plan.json")
    manifest = tracker.json(BUILDER_DIR / "generated_manifest.json")
    history_plan = tracker.json(BUILDER_DIR / "history_plan.json")
    tracker.pin(SCRIPT_DIR / "generated" / "history_manifest.json")
    tracker.pin(SCRIPT_DIR / "generated" / "ownership_intervals.csv")
    compatibility = tracker.json(SCRIPT_DIR / "main_compatibility_contract.json")
    asset_manifest = tracker.json(ASSET_DIR / "generated_asset_manifest.json")
    matrix_path = main_mod / "tools" / "jxp_runtime_acceptance" / "runtime_scenarios.json"
    # The matrix records the finished oracle-pack SHA-256, so pinning the whole
    # matrix byte stream inside that same pack would create an impossible hash
    # cycle.  Read it stably, derive only the R12 executable-checklist semantic
    # projection used by this builder, and seal that projection below.  Changes
    # to unrelated matrix metadata (including the pack SHA itself) then leave
    # the pack stable, while any change to an oracle-authoring R12 input still
    # changes the semantic pin and generated bytes.
    matrix_bytes = matrix_path.read_bytes()
    if matrix_path.read_bytes() != matrix_bytes:
        raise RuntimeError("Runtime matrix changed while deriving the R12 oracle contract")
    matrix = json.loads(matrix_bytes.decode("utf-8-sig"))
    checklist = find_r12(matrix)
    matrix_semantic_pin = {
        "path": tracker.key(matrix_path),
        "projection": "/scenarios[id=R12]/executable_checklist",
        "sha256": object_sha256(checklist),
    }

    # Pin scripts and contracts that author the checked-in generated inputs.
    for path in (
        BUILDER_DIR / "build_map.py",
        BUILDER_DIR / "build_history.py",
        ASSET_DIR / "build_assets.py",
        ASSET_DIR / "asset_plan.json",
        MOD_ROOT / "interface" / "jxp_map_assets.gfx",
        main_mod / "common" / "scripted_effects" / "jxp_77_regional_flavor_effects.txt",
        main_mod / "common" / "scripted_triggers" / "jxp_77_regional_flavor_triggers.txt",
        main_mod / "decisions" / "jxp_77_regional_flavor_decisions.txt",
    ):
        tracker.pin(path)

    province_rows, _semantic_flags = build_province_rows(tracker, plan, manifest, compatibility)
    province_ids = [row["id"] for row in province_rows]
    history_states = build_history_states(
        tracker,
        cw,
        game_root,
        main_mod,
        province_ids,
        history_plan,
        checklist,
    )
    event_options = build_event_options(
        tracker,
        cw,
        game_root,
        main_mod,
        checklist,
        asset_manifest,
    )
    origin_profiles = build_origin_profiles(
        tracker,
        cw,
        main_mod,
        checklist,
        compatibility,
        asset_manifest,
    )
    unification = build_unification(tracker, cw, main_mod, province_rows)

    if len(unification["province_rows"]) != 88:
        raise RuntimeError("Unification oracle does not contain 88 province rows")
    mission_count = sum(len(profile["missions"]) for profile in origin_profiles)
    province_row_map = {str(row["id"]): row for row in province_rows}
    history_state_map = {row["case_id"]: row for row in history_states}
    event_option_map = {row["option_key"]: row for row in event_options}
    origin_profile_map = {row["representative_tag"]: row for row in origin_profiles}
    if len(province_row_map) != len(province_rows):
        raise RuntimeError("Duplicate province oracle key")
    if len(history_state_map) != len(history_states):
        raise RuntimeError("Duplicate history case_id")
    if len(event_option_map) != len(event_options):
        raise RuntimeError("Duplicate event option key")
    if len(origin_profile_map) != len(origin_profiles):
        raise RuntimeError("Duplicate origin representative tag")
    pack = {
        "counts": {
            "event_options": len(event_options),
            "history_states": len(history_states),
            "origin_missions": mission_count,
            "origin_profiles": len(origin_profiles),
            "province_rows": len(province_rows),
            "unification_rows": len(unification["province_rows"]),
        },
        "event_options": event_option_map,
        "history_contract": {
            "campaign_end_exclusive": history_plan["campaign_end_exclusive"],
            "campaign_start": history_plan["campaign_start"],
            "relationship_interval_rule": "start_inclusive <= selected_date < end_exclusive",
        },
        "history_states": history_state_map,
        "origin_profiles": origin_profile_map,
        "province_rows": province_row_map,
        "runtime_observation_only": {
            "event_random_target": "jxp_map.22.a exact random_owned_province target; statically only owned + has_port is known",
            "mtth_dates": "exact firing dates/random rolls for MTTH events, including jxp_map.1-.10, .101, and .102",
            "render_and_visual": "engine rendering, label readability, UI layout, colour/border refresh, port/strait directionality, and click targets",
            "save_reload": "serialization, reload persistence, and absence of duplicates over the required twelve-month runtime window",
        },
        "runtime_matrix_semantic_pin": matrix_semantic_pin,
        "schema": "jxp_runtime_oracle_pack/v1",
        "source_pins": dict(sorted(tracker.hashes.items())),
        "unification": unification,
    }
    expected_counts = {
        "event_options": 37,
        "history_states": 63,
        "origin_missions": 33,
        "origin_profiles": 5,
        "province_rows": 88,
        "unification_rows": 88,
    }
    if pack["counts"] != expected_counts:
        raise RuntimeError(f"Oracle count contract drift: {pack['counts']} != {expected_counts}")
    return pack


def main() -> int:
    args = parse_args()
    output = args.output.resolve()
    try:
        pack = build_pack(args.game_root, args.main_mod)
        generated = canonical_json(pack, pretty=True)
    except Exception as exc:
        print(f"ERROR: runtime oracle generation failed: {exc}", file=sys.stderr)
        return 1

    if args.check:
        if not output.is_file():
            print(f"ERROR: runtime oracle pack is missing: {output}", file=sys.stderr)
            return 1
        committed = output.read_bytes()
        if committed != generated:
            print(
                f"ERROR: runtime oracle pack drifted: {output}\n"
                "Run build_runtime_oracles.py without --check using the same roots.",
                file=sys.stderr,
            )
            return 1
        print(
            "Runtime oracle pack is current: "
            f"88 provinces, 63 history states, 37 event options, 5 origins/33 missions, 88 unification rows"
        )
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    if output.is_file() and output.read_bytes() == generated:
        print(f"Runtime oracle pack already current: {output}")
        return 0
    temporary = output.with_suffix(output.suffix + ".tmp")
    temporary.write_bytes(generated)
    temporary.replace(output)
    print(f"Wrote runtime oracle pack: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
