#!/usr/bin/env python3
"""Build the central Agent A socioeconomic migration and in-game guide.

The domain builders own estates, markets/companies and mission profiles.  This
builder only composes their public effects into one idempotent transaction and
provides a player-facing Chinese guide.  Generated files must not be edited by
hand.
"""

from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path
import sys


MOD_ROOT = Path(__file__).resolve().parents[2]
REPO_ROOT = MOD_ROOT.parent

TRIGGER_PATH = Path("common/scripted_triggers/jxp_a_106_socioeconomic_integration_triggers.txt")
EFFECT_PATH = Path("common/scripted_effects/jxp_a_106_socioeconomic_integration_effects.txt")
EVENT_PATH = Path("events/jxp_a_106_socioeconomic_integration_events.txt")
ON_ACTION_PATH = Path("common/on_actions/jxp_a_106_socioeconomic_integration_on_actions.txt")
DECISION_PATH = Path("decisions/jxp_a_106_socioeconomic_guide_decisions.txt")
SOURCE_LOC_PATH = Path("localisation_source/jxp_a_106_socioeconomic_guide_l_english_utf8_source.yml")
ACTIVE_LOC_PATH = Path("localisation/jxp_a_106_socioeconomic_guide_l_english.yml")

GENERATED_HEADER = "# Generated by build_integration.py. Do not edit.\n"


# These flags can surface through EU4's generated trigger/effect tooltips.  Keep
# their player-facing names in one authoritative source so the interface never
# falls back to raw implementation keys.
PLAYER_VISIBLE_STATE_LABELS = {
    "jxp_a_105_legacy_capital_depth_1": "旧任务进度：首府经营（一）",
    "jxp_a_105_legacy_capital_depth_2": "旧任务进度：首府经营（二）",
    "jxp_a_105_legacy_capital_depth_3": "旧任务进度：首府经营（三）",
    "jxp_a_105_legacy_capital_depth_4": "旧任务进度：首府经营（四）",
    "jxp_a_105_legacy_capital_depth_5": "旧任务进度：首府经营（五）",
    "jxp_a_105_legacy_capital_depth_6": "旧任务进度：首府经营（六）",
    "jxp_a_105_legacy_capital_depth_7": "旧任务进度：首府经营（七）",
    "jxp_a_105_legacy_route_depth_1": "旧任务进度：国体路线（一）",
    "jxp_a_105_legacy_route_depth_2": "旧任务进度：国体路线（二）",
    "jxp_a_105_legacy_route_depth_3": "旧任务进度：国体路线（三）",
    "jxp_a_105_legacy_route_depth_4": "旧任务进度：国体路线（四）",
    "jxp_a_105_legacy_route_depth_5": "旧任务进度：国体路线（五）",
    "jxp_a_105_legacy_route_depth_6": "旧任务进度：国体路线（六）",
    "jxp_a_105_legacy_route_depth_7": "旧任务进度：国体路线（七）",
    "jxp_a_105_legacy_route_depth_8": "旧任务进度：国体路线（八）",
    "jxp_iface_a_domestic_uncommitted_ready": "国内国体就绪：天下公议尚未定制",
    "jxp_iface_a_domestic_sakoku_ready": "国内国体就绪：锁国体制",
    "jxp_iface_a_domestic_open_ready": "国内国体就绪：开国体制",
    "jxp_iface_a_domestic_buddhist_ready": "国内国体就绪：王法佛法",
    "jxp_iface_a_domestic_kirishitan_ready": "国内国体就绪：吉利支丹",
    "jxp_iface_a_domestic_confucian_ready": "国内国体就绪：礼制经世",
    "jxp_iface_a_domestic_imperial_ready": "国内国体就绪：王政太政官",
    "jxp_iface_a_domestic_reformed_ready": "国内国体就绪：改革宗盟约",
    "jxp_iface_a_domestic_kaikyo_ready": "国内国体就绪：海商回教",
    "jxp_iface_a_domestic_ikko_ready": "国内国体就绪：一向门徒共同体",
    "jxp_iface_a_domestic_wokou_ready": "国内国体就绪：倭寇海盟",
    "jxp_iface_a_domestic_toyotomi_ready": "国内国体就绪：丰臣奉行体制",
    "jxp_iface_a_domestic_commercial_council_ready": "国内国体就绪：商议会社国家",
    "jxp_a_unification_method_blade": "统一来路：军锋上洛",
    "jxp_a_unification_method_edict": "统一来路：奉敕讨不庭",
    "jxp_a_unification_method_league": "统一来路：会盟诸侯",
    "jxp_a_105_commercial_branch_shogunate": "商议分支：幕府监督",
    "jxp_a_105_commercial_branch_merchant": "商议分支：町众共和",
    "jxp_a_105_commercial_branch_company": "商议分支：会社帝国",
    "jxp_a_105_commercial_crisis_unlocked": "商本与武家争权危机已经解锁",
    "jxp_a_105_commercial_crisis_outcome_four_estates": "商议裁决：四阶层共议",
    "jxp_a_105_commercial_crisis_outcome_civil_conflict": "商议裁决：内战决胜",
    "jxp_a_105_commercial_crisis_outcome_nationalisation": "商议裁决：会社国有",
    "jxp_a_105_commercial_crisis_outcome_company_oligarchy": "商议裁决：会社寡头",
    "jxp_a_105_commercial_crisis_outcome_merchant_franchise": "商议裁决：町众参政",
    "jxp_a_105_commercial_crisis_outcome_warrior_restoration": "商议裁决：武家复权",
    "jxp_a_105_commercial_state_shareholding": "会社国体：国家持股",
    "jxp_a_105_mining_governance_ready": "矿山治理章程已经就绪",
    "jxp_a_105_mission_replay_in_progress": "国内任务进度正在迁移重放",
    "jxp_a_105_mission_schema_v1": "国内任务进度已迁入现行版本",
    "jxp_a_105_legacy_snapshot_captured": "旧任务进度快照已经留存",
    "jxp_a_socioeconomic_migration_pending": "国内经世制度正在迁移",
    "jxp_a_socioeconomic_migration_retry_queued": "国内经世制度迁移等待重试",
    "jxp_a_socioeconomic_legacy_snapshot_ready": "国内经世旧制快照已经就绪",
    "jxp_a_106_three_capitals_ledgers_converted": "三都账簿旧制已经转换",
    "jxp_a_106_buddhist_temple_credit_converted": "寺院信用旧制已经转换",
    "jxp_estate_village_communes_present_agenda": "百姓惣村当前参与阶层议程",
}


def render_triggers() -> str:
    stage_pairs = []
    for left in range(1, 5):
        for right in range(left + 1, 5):
            stage_pairs.append(
                "\tNOT = { AND = { "
                f"has_country_flag = jxp_a_market_stage_{left} "
                f"has_country_flag = jxp_a_market_stage_{right} "
                "} }"
            )
    return GENERATED_HEADER + """
jxp_a_106_has_any_socioeconomic_state_trigger = {
\tOR = {
\t\thas_country_flag = jxp_iface_a_estates_ready
\t\thas_country_flag = jxp_iface_a_company_core_ready
\t\thas_country_flag = jxp_iface_a_company_charter_active
\t\thas_country_flag = jxp_iface_a_company_state_route
\t\thas_country_flag = jxp_path_commercial_council
\t\thas_estate = jxp_estate_village_communes
\t\tjxp_a_any_socioeconomic_persistent_state_trigger = yes
\t\tjxp_a_105_any_persistent_state_trigger = yes
\t\thas_country_flag = jxp_a_socioeconomic_migration_pending
\t\thas_country_flag = jxp_a_socioeconomic_migration_retry_queued
\t\thas_country_flag = jxp_a_socioeconomic_legacy_snapshot_ready
\t\thas_country_flag = jxp_a_106_three_capitals_ledgers_converted
\t\thas_country_flag = jxp_a_106_buddhist_temple_credit_converted
\t}
}

jxp_a_106_market_state_consistent_trigger = {
""" + "\n".join(stage_pairs) + """
}

jxp_a_106_should_initialize_company_core_trigger = {
\tOR = {
\t\thas_country_flag = jxp_iface_a_company_core_ready
\t\tAND = {
\t\t\tjxp_is_unified_japan_state_trigger = yes
\t\t\tjxp_a_market_stage_at_least_3_trigger = yes
\t\t}
\t}
}

jxp_a_106_socioeconomic_migration_postconditions_trigger = {
\tjxp_is_japanese_polity_trigger = yes
\tNOT = { jxp_is_colonial_successor_tag_trigger = yes }
\thas_country_flag = jxp_iface_a_estates_ready
\tjxp_a_106_market_state_consistent_trigger = yes
\tjxp_a_105_founder_legacy_consistent_trigger = yes
\tjxp_a_105_unification_method_consistent_trigger = yes
\tjxp_a_105_profile_state_consistent_trigger = yes
\tOR = {
\t\tNOT = { jxp_a_106_should_initialize_company_core_trigger = yes }
\t\thas_country_flag = jxp_iface_a_company_core_ready
\t}
\tOR = {
\t\tNOT = { jxp_a_105_any_domestic_profile_trigger = yes }
\t\tAND = {
\t\t\thas_country_flag = jxp_a_105_mission_schema_v1
\t\t\tjxp_a_105_mission_profile_fingerprint_valid_trigger = yes
\t\t}
\t}
}
"""


def render_effects() -> str:
    return GENERATED_HEADER + """
jxp_a_106_clear_integration_markers_effect = {
\thidden_effect = {
\t\tclr_country_flag = jxp_a_socioeconomic_migration_v110
\t\tclr_country_flag = jxp_a_socioeconomic_migration_pending
\t\tclr_country_flag = jxp_a_socioeconomic_migration_retry_queued
\t\tclr_country_flag = jxp_a_socioeconomic_legacy_snapshot_ready
\t\tclr_country_flag = jxp_a_105_mission_schema_v1
\t\tclr_country_flag = jxp_a_105_legacy_capital_depth_1
\t\tclr_country_flag = jxp_a_105_legacy_capital_depth_2
\t\tclr_country_flag = jxp_a_105_legacy_capital_depth_3
\t\tclr_country_flag = jxp_a_105_legacy_capital_depth_4
\t\tclr_country_flag = jxp_a_105_legacy_capital_depth_5
\t\tclr_country_flag = jxp_a_105_legacy_capital_depth_6
\t\tclr_country_flag = jxp_a_105_legacy_capital_depth_7
\t\tclr_country_flag = jxp_a_105_legacy_route_depth_1
\t\tclr_country_flag = jxp_a_105_legacy_route_depth_2
\t\tclr_country_flag = jxp_a_105_legacy_route_depth_3
\t\tclr_country_flag = jxp_a_105_legacy_route_depth_4
\t\tclr_country_flag = jxp_a_105_legacy_route_depth_5
\t\tclr_country_flag = jxp_a_105_legacy_route_depth_6
\t\tclr_country_flag = jxp_a_105_legacy_route_depth_7
\t\tclr_country_flag = jxp_a_105_legacy_route_depth_8
\t}
}

jxp_a_106_full_socioeconomic_cleanup_effect = {
\thidden_effect = {
\t\tjxp_a_clear_japanese_estates_effect = yes
\t\tjxp_a_socioeconomic_full_cleanup_effect = yes
\t\tjxp_a_105_full_cleanup_effect = yes
\t\tclr_country_flag = jxp_iface_a_domestic_capstone_complete
\t\tclr_country_flag = jxp_iface_a_public_credit_ready
\t\tclr_country_flag = jxp_iface_a_company_state_route
\t\tclr_country_flag = jxp_a_socioeconomic_legacy_snapshot_ready
\t\tremove_country_modifier = jxp_three_capitals_ledgers
\t\tremove_country_modifier = jxp_a_buddhist_temple_credit
\t\tclr_country_flag = jxp_a_106_three_capitals_ledgers_converted
\t\tclr_country_flag = jxp_a_106_buddhist_temple_credit_converted
\t}
}

# Two B-reserved mission columns still serialize these old permanent rewards.
# Convert each one exactly once into the intended twenty-year bridge without
# changing the frozen mission bytes.
jxp_a_106_convert_legacy_permanent_rewards_effect = {
\thidden_effect = {
\t\tif = {
\t\t\tlimit = {
\t\t\t\thas_country_modifier = jxp_three_capitals_ledgers
\t\t\t\tNOT = { has_country_flag = jxp_a_106_three_capitals_ledgers_converted }
\t\t\t}
\t\t\tremove_country_modifier = jxp_three_capitals_ledgers
\t\t\tadd_country_modifier = { name = jxp_three_capitals_ledgers duration = 7300 }
\t\t\tset_country_flag = jxp_a_106_three_capitals_ledgers_converted
\t\t}
\t\tif = {
\t\t\tlimit = {
\t\t\t\thas_country_modifier = jxp_a_buddhist_temple_credit
\t\t\t\tNOT = { has_country_flag = jxp_a_106_buddhist_temple_credit_converted }
\t\t\t}
\t\t\tremove_country_modifier = jxp_a_buddhist_temple_credit
\t\t\tadd_country_modifier = { name = jxp_a_buddhist_temple_credit duration = 7300 }
\t\t\tset_country_flag = jxp_a_106_buddhist_temple_credit_converted
\t\t}
\t}
}

jxp_a_reconcile_socioeconomic_system_effect = {
\thidden_effect = {
\t\tif = {
\t\t\tlimit = {
\t\t\t\tjxp_is_japanese_polity_trigger = yes
\t\t\t\tNOT = { jxp_is_colonial_successor_tag_trigger = yes }
\t\t\t}
\t\t\tjxp_a_105_reconcile_founder_legacy_effect = yes
\t\t\tjxp_a_105_reconcile_unification_method_effect = yes
\t\t\tjxp_a_reconcile_japanese_estates_effect = yes
\t\t\tjxp_a_reconcile_market_stage = yes
\t\t\tif = {
\t\t\t\tlimit = { jxp_a_106_should_initialize_company_core_trigger = yes }
\t\t\t\tjxp_a_initialize_company_core_effect = yes
\t\t\t}
\t\t\tjxp_a_reconcile_companies_effect = yes
\t\t\tjxp_a_105_reconcile_mission_profile_effect = yes
\t\t\tjxp_a_105_reconcile_commercial_council_effect = yes
\t\t\tjxp_a_106_convert_legacy_permanent_rewards_effect = yes
\t\t}
\t\telse_if = {
\t\t\tlimit = { jxp_a_106_has_any_socioeconomic_state_trigger = yes }
\t\t\tjxp_a_106_full_socioeconomic_cleanup_effect = yes
\t\t}
\t}
}

jxp_a_run_socioeconomic_migration_effect = {
\thidden_effect = {
\t\tif = {
\t\t\tlimit = { jxp_is_colonial_successor_tag_trigger = yes }
\t\t\tjxp_a_106_full_socioeconomic_cleanup_effect = yes
\t\t\tclr_country_flag = jxp_a_socioeconomic_migration_pending
\t\t\tclr_country_flag = jxp_a_socioeconomic_migration_retry_queued
\t\t\tset_country_flag = jxp_a_socioeconomic_migration_v110
\t\t}
\t\telse_if = {
\t\t\tlimit = { jxp_is_japanese_polity_trigger = yes }
\t\t\tif = {
\t\t\t\tlimit = { NOT = { has_country_flag = jxp_a_socioeconomic_legacy_snapshot_ready } }
\t\t\t\tjxp_a_105_capture_legacy_mission_progress_effect = yes
\t\t\t\tset_country_flag = jxp_a_socioeconomic_legacy_snapshot_ready
\t\t\t}
\t\t\tjxp_a_105_reconcile_founder_legacy_effect = yes
\t\t\tjxp_a_105_reconcile_unification_method_effect = yes
\t\t\tjxp_a_reconcile_japanese_estates_effect = yes
\t\t\tjxp_a_reconcile_market_stage = yes
\t\t\tif = {
\t\t\t\tlimit = { jxp_a_106_should_initialize_company_core_trigger = yes }
\t\t\t\tjxp_a_initialize_company_core_effect = yes
\t\t\t}
\t\t\tjxp_a_reconcile_companies_effect = yes
\t\t\tjxp_a_105_reconcile_commercial_council_effect = yes
\t\t\tjxp_a_106_convert_legacy_permanent_rewards_effect = yes
\t\t\tjxp_a_105_migrate_mission_schema_effect = yes
\t\t\tif = {
\t\t\t\tlimit = { jxp_a_106_socioeconomic_migration_postconditions_trigger = yes }
\t\t\t\tclr_country_flag = jxp_a_socioeconomic_migration_pending
\t\t\t\tclr_country_flag = jxp_a_socioeconomic_migration_retry_queued
\t\t\t\tclr_country_flag = jxp_a_socioeconomic_legacy_snapshot_ready
\t\t\t\tset_country_flag = jxp_a_socioeconomic_migration_v110
\t\t\t}
\t\t\telse = {
\t\t\t\tset_country_flag = jxp_a_socioeconomic_migration_pending
\t\t\t\tif = {
\t\t\t\t\tlimit = { NOT = { has_country_flag = jxp_a_socioeconomic_migration_retry_queued } }
\t\t\t\t\tset_country_flag = jxp_a_socioeconomic_migration_retry_queued
\t\t\t\t\tcountry_event = { id = jxp_a_socioeconomic_integration.2 days = 1 }
\t\t\t\t}
\t\t\t}
\t\t}
\t\telse_if = {
\t\t\tlimit = { jxp_a_106_has_any_socioeconomic_state_trigger = yes }
\t\t\tjxp_a_106_full_socioeconomic_cleanup_effect = yes
\t\t\tclr_country_flag = jxp_a_socioeconomic_migration_pending
\t\t\tclr_country_flag = jxp_a_socioeconomic_migration_retry_queued
\t\t\tset_country_flag = jxp_a_socioeconomic_migration_v110
\t\t}
\t}
}

jxp_a_debug_reset_socioeconomic_system_effect = {
\thidden_effect = {
\t\tjxp_a_106_full_socioeconomic_cleanup_effect = yes
\t\tjxp_a_106_clear_integration_markers_effect = yes
\t}
}
"""


def render_events() -> str:
    return GENERATED_HEADER + """namespace = jxp_a_socioeconomic_integration

country_event = {
\tid = jxp_a_socioeconomic_integration.1
\ttitle = none
\tdesc = none
\tpicture = COURT_eventPicture
\thidden = yes
\ttrigger = {
\t\tOR = {
\t\t\tAND = {
\t\t\t\tjxp_is_japanese_polity_trigger = yes
\t\t\t\tNOT = { has_country_flag = jxp_a_socioeconomic_migration_v110 }
\t\t\t}
\t\t\thas_country_flag = jxp_a_socioeconomic_migration_pending
\t\t\tAND = {
\t\t\t\tjxp_a_106_has_any_socioeconomic_state_trigger = yes
\t\t\t\tNOT = { jxp_is_japanese_polity_trigger = yes }
\t\t\t}
\t\t}
\t}
\timmediate = { jxp_a_run_socioeconomic_migration_effect = yes }
\toption = { name = "OK" }
}

country_event = {
\tid = jxp_a_socioeconomic_integration.2
\ttitle = none
\tdesc = none
\tpicture = COURT_eventPicture
\thidden = yes
\tis_triggered_only = yes
\ttrigger = {
\t\thas_country_flag = jxp_a_socioeconomic_migration_pending
\t\thas_country_flag = jxp_a_socioeconomic_migration_retry_queued
\t}
\timmediate = {
\t\tclr_country_flag = jxp_a_socioeconomic_migration_retry_queued
\t\tjxp_a_run_socioeconomic_migration_effect = yes
\t}
\toption = { name = "OK" }
}

country_event = {
\tid = jxp_a_socioeconomic_integration.100
\ttitle = jxp_a_socioeconomic_integration.100.t
\tdesc = jxp_a_socioeconomic_integration.100.d
\tpicture = MERCHANTS_TALKING_eventPicture
\tis_triggered_only = yes
\toption = { name = jxp_a_socioeconomic_integration.100.estates country_event = { id = jxp_a_socioeconomic_integration.101 } }
\toption = { name = jxp_a_socioeconomic_integration.100.market country_event = { id = jxp_a_socioeconomic_integration.102 } }
\toption = { name = jxp_a_socioeconomic_integration.100.companies country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.100.routes country_event = { id = jxp_a_socioeconomic_integration.104 } }
\toption = { name = jxp_a_socioeconomic_integration.100.identity country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.close }
}

country_event = {
\tid = jxp_a_socioeconomic_integration.101
\ttitle = jxp_a_socioeconomic_integration.101.t
\tdesc = jxp_a_socioeconomic_integration.101.d
\tpicture = COURT_eventPicture
\tis_triggered_only = yes
\toption = { name = jxp_a_socioeconomic_integration.estate.nobles trigger = { has_estate = estate_nobles } country_event = { id = jxp_a_socioeconomic_integration.101 } }
\toption = { name = jxp_a_socioeconomic_integration.estate.church trigger = { has_estate = estate_church } country_event = { id = jxp_a_socioeconomic_integration.101 } }
\toption = { name = jxp_a_socioeconomic_integration.estate.burghers trigger = { has_estate = estate_burghers } country_event = { id = jxp_a_socioeconomic_integration.101 } }
\toption = { name = jxp_a_socioeconomic_integration.estate.communes trigger = { has_estate = jxp_estate_village_communes } country_event = { id = jxp_a_socioeconomic_integration.101 } }
\toption = { name = jxp_a_socioeconomic_integration.estate.unready trigger = { NOT = { has_country_flag = jxp_iface_a_estates_ready } } country_event = { id = jxp_a_socioeconomic_integration.101 } }
\toption = { name = jxp_a_socioeconomic_integration.back country_event = { id = jxp_a_socioeconomic_integration.100 } }
}

country_event = {
\tid = jxp_a_socioeconomic_integration.102
\ttitle = jxp_a_socioeconomic_integration.102.t
\tdesc = jxp_a_socioeconomic_integration.102.d
\tpicture = MERCHANTS_TALKING_eventPicture
\tis_triggered_only = yes
\toption = { name = jxp_a_socioeconomic_integration.stage.none trigger = { NOT = { OR = { has_country_flag = jxp_a_market_stage_1 has_country_flag = jxp_a_market_stage_2 has_country_flag = jxp_a_market_stage_3 has_country_flag = jxp_a_market_stage_4 } } } country_event = { id = jxp_a_socioeconomic_integration.100 } }
\toption = { name = jxp_a_socioeconomic_integration.stage.1 trigger = { has_country_flag = jxp_a_market_stage_1 } country_event = { id = jxp_a_socioeconomic_integration.100 } }
\toption = { name = jxp_a_socioeconomic_integration.stage.2 trigger = { has_country_flag = jxp_a_market_stage_2 } country_event = { id = jxp_a_socioeconomic_integration.100 } }
\toption = { name = jxp_a_socioeconomic_integration.stage.3 trigger = { has_country_flag = jxp_a_market_stage_3 } country_event = { id = jxp_a_socioeconomic_integration.100 } }
\toption = { name = jxp_a_socioeconomic_integration.stage.4 trigger = { has_country_flag = jxp_a_market_stage_4 } country_event = { id = jxp_a_socioeconomic_integration.100 } }
\toption = { name = jxp_a_socioeconomic_integration.credit.ready trigger = { has_country_flag = jxp_iface_a_public_credit_ready } country_event = { id = jxp_a_socioeconomic_integration.102 } }
\toption = { name = jxp_a_socioeconomic_integration.credit.unready trigger = { NOT = { has_country_flag = jxp_iface_a_public_credit_ready } } country_event = { id = jxp_a_socioeconomic_integration.102 } }
\toption = { name = jxp_a_socioeconomic_integration.back country_event = { id = jxp_a_socioeconomic_integration.100 } }
}

country_event = {
\tid = jxp_a_socioeconomic_integration.103
\ttitle = jxp_a_socioeconomic_integration.103.t
\tdesc = jxp_a_socioeconomic_integration.103.d
\tpicture = MERCHANTS_TALKING_eventPicture
\tis_triggered_only = yes
\toption = { name = jxp_a_socioeconomic_integration.company.none trigger = { NOT = { OR = { has_country_flag = jxp_a_company_mining_chartered has_country_flag = jxp_a_company_shipping_chartered has_country_flag = jxp_a_company_rice_credit_chartered has_country_flag = jxp_a_company_textile_chartered has_country_flag = jxp_a_company_armaments_chartered has_country_flag = jxp_a_company_mining_nationalized has_country_flag = jxp_a_company_shipping_nationalized has_country_flag = jxp_a_company_rice_credit_nationalized has_country_flag = jxp_a_company_textile_nationalized has_country_flag = jxp_a_company_armaments_nationalized } } } country_event = { id = jxp_a_socioeconomic_integration.100 } }
\toption = { name = jxp_a_socioeconomic_integration.company.mining trigger = { has_country_flag = jxp_a_company_mining_chartered } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.company.shipping trigger = { has_country_flag = jxp_a_company_shipping_chartered } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.company.rice trigger = { has_country_flag = jxp_a_company_rice_credit_chartered } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.company.textile trigger = { has_country_flag = jxp_a_company_textile_chartered } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.company.armaments trigger = { has_country_flag = jxp_a_company_armaments_chartered } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.company.mining.nationalized trigger = { has_country_flag = jxp_a_company_mining_nationalized } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.company.shipping.nationalized trigger = { has_country_flag = jxp_a_company_shipping_nationalized } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.company.rice.nationalized trigger = { has_country_flag = jxp_a_company_rice_credit_nationalized } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.company.textile.nationalized trigger = { has_country_flag = jxp_a_company_textile_nationalized } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.company.armaments.nationalized trigger = { has_country_flag = jxp_a_company_armaments_nationalized } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.company.state.expanding trigger = { OR = { has_country_flag = jxp_a_company_mining_state_expanding has_country_flag = jxp_a_company_shipping_state_expanding has_country_flag = jxp_a_company_rice_credit_state_expanding has_country_flag = jxp_a_company_textile_state_expanding has_country_flag = jxp_a_company_armaments_state_expanding } } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.company.state.stable trigger = { OR = { has_country_flag = jxp_a_company_mining_state_stable has_country_flag = jxp_a_company_shipping_state_stable has_country_flag = jxp_a_company_rice_credit_state_stable has_country_flag = jxp_a_company_textile_state_stable has_country_flag = jxp_a_company_armaments_state_stable } } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.company.state.distressed trigger = { OR = { has_country_flag = jxp_a_company_mining_state_distressed has_country_flag = jxp_a_company_shipping_state_distressed has_country_flag = jxp_a_company_rice_credit_state_distressed has_country_flag = jxp_a_company_textile_state_distressed has_country_flag = jxp_a_company_armaments_state_distressed } } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.company.state.reformed trigger = { OR = { has_country_flag = jxp_a_company_mining_state_reformed has_country_flag = jxp_a_company_shipping_state_reformed has_country_flag = jxp_a_company_rice_credit_state_reformed has_country_flag = jxp_a_company_textile_state_reformed has_country_flag = jxp_a_company_armaments_state_reformed } } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.company.directors country_event = { id = jxp_a_socioeconomic_integration.105 } }
\toption = { name = jxp_a_socioeconomic_integration.company.overseas country_event = { id = jxp_a_socioeconomic_integration.106 } }
\toption = { name = jxp_a_socioeconomic_integration.back country_event = { id = jxp_a_socioeconomic_integration.100 } }
}

country_event = {
\tid = jxp_a_socioeconomic_integration.105
\ttitle = jxp_a_socioeconomic_integration.105.t
\tdesc = jxp_a_socioeconomic_integration.105.d
\tpicture = MERCHANTS_TALKING_eventPicture
\tis_triggered_only = yes
\toption = { name = jxp_a_socioeconomic_integration.director.state trigger = { OR = { has_country_flag = jxp_a_company_mining_director_state has_country_flag = jxp_a_company_shipping_director_state has_country_flag = jxp_a_company_rice_credit_director_state has_country_flag = jxp_a_company_textile_director_state has_country_flag = jxp_a_company_armaments_director_state } } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.director.merchant trigger = { OR = { has_country_flag = jxp_a_company_mining_director_merchant has_country_flag = jxp_a_company_shipping_director_merchant has_country_flag = jxp_a_company_rice_credit_director_merchant has_country_flag = jxp_a_company_textile_director_merchant has_country_flag = jxp_a_company_armaments_director_merchant } } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.director.warrior trigger = { OR = { has_country_flag = jxp_a_company_mining_director_warrior has_country_flag = jxp_a_company_shipping_director_warrior has_country_flag = jxp_a_company_rice_credit_director_warrior has_country_flag = jxp_a_company_textile_director_warrior has_country_flag = jxp_a_company_armaments_director_warrior } } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.director.religious trigger = { OR = { has_country_flag = jxp_a_company_mining_director_religious has_country_flag = jxp_a_company_shipping_director_religious has_country_flag = jxp_a_company_rice_credit_director_religious has_country_flag = jxp_a_company_textile_director_religious has_country_flag = jxp_a_company_armaments_director_religious } } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.director.mixed trigger = { OR = { has_country_flag = jxp_a_company_mining_director_mixed has_country_flag = jxp_a_company_shipping_director_mixed has_country_flag = jxp_a_company_rice_credit_director_mixed has_country_flag = jxp_a_company_textile_director_mixed has_country_flag = jxp_a_company_armaments_director_mixed } } country_event = { id = jxp_a_socioeconomic_integration.103 } }
\toption = { name = jxp_a_socioeconomic_integration.company.back country_event = { id = jxp_a_socioeconomic_integration.103 } }
}

country_event = {
\tid = jxp_a_socioeconomic_integration.106
\ttitle = jxp_a_socioeconomic_integration.106.t
\tdesc = jxp_a_socioeconomic_integration.106.d
\tpicture = MERCHANTS_TALKING_eventPicture
\tis_triggered_only = yes
\toption = { name = jxp_a_socioeconomic_integration.request.none trigger = { NOT = { OR = { has_country_flag = jxp_iface_a_request_red_seal_overseas_company has_country_flag = jxp_iface_a_request_pacific_charter_company has_country_flag = jxp_iface_a_request_southern_seas_company has_country_flag = jxp_iface_a_request_northern_seas_company has_country_flag = jxp_iface_a_request_continental_company } } } country_event = { id = jxp_a_socioeconomic_integration.106 } }
\toption = { name = jxp_a_socioeconomic_integration.request.red_seal trigger = { has_country_flag = jxp_iface_a_request_red_seal_overseas_company } country_event = { id = jxp_a_socioeconomic_integration.106 } }
\toption = { name = jxp_a_socioeconomic_integration.request.pacific trigger = { has_country_flag = jxp_iface_a_request_pacific_charter_company } country_event = { id = jxp_a_socioeconomic_integration.106 } }
\toption = { name = jxp_a_socioeconomic_integration.request.southern trigger = { has_country_flag = jxp_iface_a_request_southern_seas_company } country_event = { id = jxp_a_socioeconomic_integration.106 } }
\toption = { name = jxp_a_socioeconomic_integration.request.northern trigger = { has_country_flag = jxp_iface_a_request_northern_seas_company } country_event = { id = jxp_a_socioeconomic_integration.106 } }
\toption = { name = jxp_a_socioeconomic_integration.request.continental trigger = { has_country_flag = jxp_iface_a_request_continental_company } country_event = { id = jxp_a_socioeconomic_integration.106 } }
\toption = { name = jxp_a_socioeconomic_integration.company.back country_event = { id = jxp_a_socioeconomic_integration.103 } }
}

country_event = {
\tid = jxp_a_socioeconomic_integration.104
\ttitle = jxp_a_socioeconomic_integration.104.t
\tdesc = jxp_a_socioeconomic_integration.104.d
\tpicture = COURT_eventPicture
\tis_triggered_only = yes
\toption = { name = jxp_a_socioeconomic_integration.route.commercial trigger = { has_country_flag = jxp_path_commercial_council } country_event = { id = jxp_a_socioeconomic_integration.100 } }
\toption = { name = jxp_a_socioeconomic_integration.route.available trigger = { jxp_a_105_can_enter_commercial_council_trigger = yes } country_event = { id = jxp_a_socioeconomic_integration.100 } }
\toption = { name = jxp_a_socioeconomic_integration.route.unavailable trigger = { NOT = { has_country_flag = jxp_path_commercial_council } NOT = { jxp_a_105_can_enter_commercial_council_trigger = yes } } country_event = { id = jxp_a_socioeconomic_integration.100 } }
\toption = { name = jxp_a_socioeconomic_integration.capstone.complete trigger = { has_country_flag = jxp_iface_a_domestic_capstone_complete } country_event = { id = jxp_a_socioeconomic_integration.104 } }
\toption = { name = jxp_a_socioeconomic_integration.capstone.incomplete trigger = { NOT = { has_country_flag = jxp_iface_a_domestic_capstone_complete } } country_event = { id = jxp_a_socioeconomic_integration.104 } }
\toption = { name = jxp_a_socioeconomic_integration.back country_event = { id = jxp_a_socioeconomic_integration.100 } }
}

country_event = {
\tid = jxp_a_socioeconomic_integration.107
\ttitle = jxp_a_socioeconomic_integration.107.t
\tdesc = jxp_a_socioeconomic_integration.107.d
\tpicture = COURT_eventPicture
\tis_triggered_only = yes
\toption = { name = jxp_a_socioeconomic_integration.identity.daimyo trigger = { jxp_is_daimyo_stage_trigger = yes } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.uncommitted trigger = { jxp_a_105_profile_uncommitted_trigger = yes } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.sakoku trigger = { jxp_a_105_profile_sakoku_trigger = yes } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.open trigger = { jxp_a_105_profile_open_trigger = yes } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.buddhist trigger = { jxp_a_105_profile_buddhist_trigger = yes } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.kirishitan trigger = { jxp_a_105_profile_kirishitan_trigger = yes } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.confucian trigger = { jxp_a_105_profile_confucian_trigger = yes } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.imperial trigger = { jxp_a_105_profile_imperial_trigger = yes } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.reformed trigger = { jxp_a_105_profile_reformed_trigger = yes } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.kaikyo trigger = { jxp_a_105_profile_kaikyo_trigger = yes } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.ikko trigger = { jxp_a_105_profile_ikko_trigger = yes } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.wokou trigger = { jxp_a_105_profile_wokou_trigger = yes } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.toyotomi trigger = { jxp_a_105_profile_toyotomi_trigger = yes } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.commercial trigger = { jxp_a_105_profile_commercial_council_trigger = yes } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.branch.foundation trigger = { has_reform = jxp_a_105_commercial_council_state_reform } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.branch.shogunate trigger = { has_country_flag = jxp_a_105_commercial_branch_shogunate } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.branch.merchant trigger = { has_country_flag = jxp_a_105_commercial_branch_merchant } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.branch.company trigger = { has_country_flag = jxp_a_105_commercial_branch_company } country_event = { id = jxp_a_socioeconomic_integration.107 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.founder country_event = { id = jxp_a_socioeconomic_integration.108 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.unification country_event = { id = jxp_a_socioeconomic_integration.109 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.era country_event = { id = jxp_a_socioeconomic_integration.110 } }
\toption = { name = jxp_a_socioeconomic_integration.back country_event = { id = jxp_a_socioeconomic_integration.100 } }
}

country_event = {
\tid = jxp_a_socioeconomic_integration.108
\ttitle = jxp_a_socioeconomic_integration.108.t
\tdesc = jxp_a_socioeconomic_integration.108.d
\tpicture = COURT_eventPicture
\tis_triggered_only = yes
\toption = { name = jxp_a_socioeconomic_integration.founder.commercial trigger = { has_country_flag = jxp_iface_a_founder_commercial_legacy } country_event = { id = jxp_a_socioeconomic_integration.108 } }
\toption = { name = jxp_a_socioeconomic_integration.founder.maritime trigger = { has_country_flag = jxp_iface_a_founder_maritime_legacy } country_event = { id = jxp_a_socioeconomic_integration.108 } }
\toption = { name = jxp_a_socioeconomic_integration.founder.bureaucratic trigger = { has_country_flag = jxp_iface_a_founder_bureaucratic_legacy } country_event = { id = jxp_a_socioeconomic_integration.108 } }
\toption = { name = jxp_a_socioeconomic_integration.founder.communal trigger = { has_country_flag = jxp_iface_a_founder_communal_legacy } country_event = { id = jxp_a_socioeconomic_integration.108 } }
\toption = { name = jxp_a_socioeconomic_integration.founder.frontier trigger = { has_country_flag = jxp_iface_a_founder_frontier_legacy } country_event = { id = jxp_a_socioeconomic_integration.108 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.back country_event = { id = jxp_a_socioeconomic_integration.107 } }
}

country_event = {
\tid = jxp_a_socioeconomic_integration.109
\ttitle = jxp_a_socioeconomic_integration.109.t
\tdesc = jxp_a_socioeconomic_integration.109.d
\tpicture = BATTLE_eventPicture
\tis_triggered_only = yes
\toption = { name = jxp_a_socioeconomic_integration.unification.blade trigger = { has_country_flag = jxp_a_unification_method_blade } country_event = { id = jxp_a_socioeconomic_integration.109 } }
\toption = { name = jxp_a_socioeconomic_integration.unification.edict trigger = { has_country_flag = jxp_a_unification_method_edict } country_event = { id = jxp_a_socioeconomic_integration.109 } }
\toption = { name = jxp_a_socioeconomic_integration.unification.league trigger = { has_country_flag = jxp_a_unification_method_league } country_event = { id = jxp_a_socioeconomic_integration.109 } }
\toption = { name = jxp_a_socioeconomic_integration.unification.pending trigger = { NOT = { OR = { has_country_flag = jxp_a_unification_method_blade has_country_flag = jxp_a_unification_method_edict has_country_flag = jxp_a_unification_method_league } } } country_event = { id = jxp_a_socioeconomic_integration.109 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.back country_event = { id = jxp_a_socioeconomic_integration.107 } }
}

country_event = {
\tid = jxp_a_socioeconomic_integration.110
\ttitle = jxp_a_socioeconomic_integration.110.t
\tdesc = jxp_a_socioeconomic_integration.110.d
\tpicture = COURT_eventPicture
\tis_triggered_only = yes
\toption = { name = jxp_a_socioeconomic_integration.era.tenka.high trigger = { jxp_tenka_order_at_least_75 = yes } country_event = { id = jxp_a_socioeconomic_integration.110 } }
\toption = { name = jxp_a_socioeconomic_integration.era.tenka.middle trigger = { jxp_tenka_order_at_least_25 = yes NOT = { jxp_tenka_order_at_least_75 = yes } } country_event = { id = jxp_a_socioeconomic_integration.110 } }
\toption = { name = jxp_a_socioeconomic_integration.era.tenka.low trigger = { NOT = { jxp_tenka_order_at_least_25 = yes } } country_event = { id = jxp_a_socioeconomic_integration.110 } }
\toption = { name = jxp_a_socioeconomic_integration.era.sanction.high trigger = { jxp_imperial_sanction_at_least_70 = yes } country_event = { id = jxp_a_socioeconomic_integration.110 } }
\toption = { name = jxp_a_socioeconomic_integration.era.sanction.middle trigger = { jxp_imperial_sanction_at_least_30 = yes NOT = { jxp_imperial_sanction_at_least_70 = yes } } country_event = { id = jxp_a_socioeconomic_integration.110 } }
\toption = { name = jxp_a_socioeconomic_integration.era.sanction.low trigger = { NOT = { jxp_imperial_sanction_at_least_30 = yes } } country_event = { id = jxp_a_socioeconomic_integration.110 } }
\toption = { name = jxp_a_socioeconomic_integration.era.ocean.high trigger = { jxp_oceanic_opening_at_least_75 = yes } country_event = { id = jxp_a_socioeconomic_integration.110 } }
\toption = { name = jxp_a_socioeconomic_integration.era.ocean.middle trigger = { jxp_oceanic_opening_at_least_20 = yes NOT = { jxp_oceanic_opening_at_least_75 = yes } } country_event = { id = jxp_a_socioeconomic_integration.110 } }
\toption = { name = jxp_a_socioeconomic_integration.era.ocean.low trigger = { NOT = { jxp_oceanic_opening_at_least_20 = yes } } country_event = { id = jxp_a_socioeconomic_integration.110 } }
\toption = { name = jxp_a_socioeconomic_integration.identity.back country_event = { id = jxp_a_socioeconomic_integration.107 } }
}
"""


def render_on_actions() -> str:
    return GENERATED_HEADER + """
on_startup = {
\tevents = { jxp_a_socioeconomic_integration.1 }
}

# A failed transaction receives one one-day retry from event .2 and thereafter
# only this bounded yearly retry.  There is no monthly or world scan.
on_yearly_pulse = {
\tevents = { jxp_a_socioeconomic_integration.1 }
\tif = {
\t\tlimit = {
\t\t\tjxp_is_japanese_polity_trigger = yes
\t\t\tOR = {
\t\t\t\tAND = {
\t\t\t\t\thas_country_modifier = jxp_three_capitals_ledgers
\t\t\t\t\tNOT = { has_country_flag = jxp_a_106_three_capitals_ledgers_converted }
\t\t\t\t}
\t\t\t\tAND = {
\t\t\t\t\thas_country_modifier = jxp_a_buddhist_temple_credit
\t\t\t\t\tNOT = { has_country_flag = jxp_a_106_buddhist_temple_credit_converted }
\t\t\t\t}
\t\t\t}
\t\t}
\t\tjxp_a_106_convert_legacy_permanent_rewards_effect = yes
\t}
}

on_religion_change = {
\tif = {
\t\tlimit = { OR = { jxp_is_japanese_polity_trigger = yes jxp_a_106_has_any_socioeconomic_state_trigger = yes } }
\t\tjxp_a_reconcile_socioeconomic_system_effect = yes
\t}
}

on_government_change = {
\tif = {
\t\tlimit = { OR = { jxp_is_japanese_polity_trigger = yes jxp_a_106_has_any_socioeconomic_state_trigger = yes } }
\t\tjxp_a_reconcile_socioeconomic_system_effect = yes
\t}
}
"""


def render_decisions() -> str:
    return GENERATED_HEADER + """country_decisions = {
\tjxp_a_open_socioeconomic_gazetteer = {
\t\tmajor = no
\t\tpotential = {
\t\t\tOR = {
\t\t\t\tjxp_is_japanese_polity_trigger = yes
\t\t\t\tjxp_a_106_has_any_socioeconomic_state_trigger = yes
\t\t\t}
\t\t}
\t\tallow = { always = yes }
\t\teffect = { country_event = { id = jxp_a_socioeconomic_integration.100 } }
\t\tai_will_do = { factor = 0 }
\t}
}
"""


def render_localisation() -> str:
    lines = [
        "l_english:",
        ' jxp_a_open_socioeconomic_gazetteer_title:0 "阅览国体图志"',
        ' jxp_a_open_socioeconomic_gazetteer_desc:0 "召集奉行、阶层惣代与商事书役，查阅本国四阶层、商市阶段、会社章程及国内终局的现况。此举只打开说明，不改变任何国策。"',
        ' jxp_a_socioeconomic_integration.100.t:0 "国体图志：邦内经世总览"',
        ' jxp_a_socioeconomic_integration.100.d:0 "天下之财用，不独在仓廪金银，亦系于武家之奉公、寺社之公议、町众之信用与百姓之耕织。图志分录四阶层、商市成网、会社章程及终局国体；海外商馆、殖民与大陆经营仍由另册办理。"',
        ' jxp_a_socioeconomic_integration.100.estates:0 "查看四阶层与权利"',
        ' jxp_a_socioeconomic_integration.100.market:0 "查看商市与信用阶段"',
        ' jxp_a_socioeconomic_integration.100.companies:0 "查看现行会社章程"',
        ' jxp_a_socioeconomic_integration.100.routes:0 "查看国内终局与商业公议"',
        ' jxp_a_socioeconomic_integration.101.t:0 "四阶层之议"',
        ' jxp_a_socioeconomic_integration.101.d:0 "武家奉公众掌军役与知行，寺社宗门维持教化、施济与寺领，町众豪商经营市庭、信用与廻船，百姓惣村承担年贡、普请与乡村生产。各项特权皆有忠诚、影响力与领地代价；阶层势力失衡会引出家中割据、宗门公议崩溃、豪商专政或德政惣动。路线改易后，失去法理的特权由中央清册撤除。"',
        ' jxp_a_socioeconomic_integration.102.t:0 "商市、信用、工场与会社"',
        ' jxp_a_socioeconomic_integration.102.d:0 "商业化依次经历商市成网、信用成制、工场成业、会社成国。阶段平常只进不退，且须同时具备城市、生产、年代、技术及至少两项天下属性支持；破产与危机带来代价，却不会让普通改换路线重复领取阶段赏赐。"',
        ' jxp_a_socioeconomic_integration.103.t:0 "会社章程录"',
        ' jxp_a_socioeconomic_integration.103.d:0 "每家会社都须申请章程、募集本钱、选定董事、接受年度账目与到期审议。国小者至多一社，市场渐成可扩为二、三社；唯会社成国或商议日本可容四社，并承受豪商干政、武家反弹与破产风险。国内会社绝不自行取得海外领土；海外业务只发出接口请求。"',
        ' jxp_a_socioeconomic_integration.104.t:0 "国内终局与商议之途"',
        ' jxp_a_socioeconomic_integration.104.d:0 "十二种统一国体各有自己的财用法、阶层妥协、危机与唯一国内大成。商议日本则是明确的分歧历史：统一后的武家国家若已形成信用、工场、两家会社与强势而忠诚的町众，方可让奉行、城市、公司与四阶层共同议政。此路门槛严苛，选定后将排除其他极端国体，并可能爆发商本与武家俸禄危机。"',
        ' jxp_a_socioeconomic_integration.stage.none:0 "当前：商市尚未成网"',
        ' jxp_a_socioeconomic_integration.stage.1:0 "当前：商市成网"',
        ' jxp_a_socioeconomic_integration.stage.2:0 "当前：信用成制"',
        ' jxp_a_socioeconomic_integration.stage.3:0 "当前：工场成业"',
        ' jxp_a_socioeconomic_integration.stage.4:0 "当前：会社成国"',
        ' jxp_a_socioeconomic_integration.credit.ready:0 "公共信用：全国担保与公债制度已经成立"',
        ' jxp_a_socioeconomic_integration.credit.unready:0 "公共信用：尚未形成可供天下共信的担保"',
        ' jxp_a_socioeconomic_integration.company.none:0 "当前没有有效会社章程"',
        ' jxp_a_socioeconomic_integration.company.mining:0 "金银山会所：章程有效"',
        ' jxp_a_socioeconomic_integration.company.shipping:0 "全国廻船会所：章程有效"',
        ' jxp_a_socioeconomic_integration.company.rice:0 "米市信用会所：章程有效"',
        ' jxp_a_socioeconomic_integration.company.textile:0 "织造会社：章程有效"',
        ' jxp_a_socioeconomic_integration.company.armaments:0 "军需造船会社：章程有效"',
        ' jxp_a_socioeconomic_integration.director.state:0 "董事席：至少一社由国家奉行主导"',
        ' jxp_a_socioeconomic_integration.director.merchant:0 "董事席：至少一社由町众豪商主导"',
        ' jxp_a_socioeconomic_integration.director.warrior:0 "董事席：至少一社由武家奉公众主导"',
        ' jxp_a_socioeconomic_integration.director.religious:0 "董事席：至少一社由寺社宗门主导"',
        ' jxp_a_socioeconomic_integration.director.mixed:0 "董事席：至少一社采用混合评议"',
        ' jxp_a_socioeconomic_integration.route.commercial:0 "当前国体：商议日本／天下会社国"',
        ' jxp_a_socioeconomic_integration.route.available:0 "商议之途已经具备法理与财用条件"',
        ' jxp_a_socioeconomic_integration.route.unavailable:0 "商议之途尚缺统一、信用、会社或阶层支持"',
        ' jxp_a_socioeconomic_integration.capstone.complete:0 "国内大成：当前国体的经世工程已经完成"',
        ' jxp_a_socioeconomic_integration.capstone.incomplete:0 "国内大成：当前国体的经世工程尚未完成"',
        ' jxp_a_socioeconomic_integration.back:0 "返回总览"',
        ' jxp_a_socioeconomic_integration.close:0 "合上图志"',
        ' jxp_iface_a_estates_ready:0 "日本四阶层已经整编"',
        ' jxp_iface_a_company_core_ready:0 "会社章程制度已经建立"',
        ' jxp_iface_a_company_charter_active:0 "至少一家会社章程有效"',
        ' jxp_iface_a_domestic_capstone_complete:0 "当前国内终局工程已经完成"',
        ' jxp_iface_a_public_credit_ready:0 "全国公共信用已经成立"',
        ' jxp_iface_a_company_state_route:0 "商议日本国体"',
        ' jxp_iface_a_founder_commercial_legacy:0 "创始家遗产：城市与市场"',
        ' jxp_iface_a_founder_maritime_legacy:0 "创始家遗产：海商与港口"',
        ' jxp_iface_a_founder_bureaucratic_legacy:0 "创始家遗产：官僚与检地"',
        ' jxp_iface_a_founder_communal_legacy:0 "创始家遗产：共同体与寺社"',
        ' jxp_iface_a_founder_frontier_legacy:0 "创始家遗产：边疆与资源"',
        ' jxp_path_commercial_council:0 "商议日本路线"',
        ' jxp_a_market_stage_1:0 "商市成网"',
        ' jxp_a_market_stage_2:0 "信用成制"',
        ' jxp_a_market_stage_3:0 "工场成业"',
        ' jxp_a_market_stage_4:0 "会社成国"',
    ]
    # Market-stage display keys are owned by the economy builder.  This guide
    # owns only the shared interface labels, so a source-to-active build never
    # creates duplicate localisation keys.
    lines = [
        line
        for line in lines
        if not any(
            line.startswith(f" jxp_a_market_stage_{stage}:0 ")
            for stage in range(1, 5)
        )
    ]

    replacements = {
        "jxp_a_socioeconomic_integration.company.mining": "金银山会所：章程有效（期限详见国家修正）",
        "jxp_a_socioeconomic_integration.company.shipping": "全国廻船会所：章程有效（期限详见国家修正）",
        "jxp_a_socioeconomic_integration.company.rice": "米市信用会所：章程有效（期限详见国家修正）",
        "jxp_a_socioeconomic_integration.company.textile": "织造会社：章程有效（期限详见国家修正）",
        "jxp_a_socioeconomic_integration.company.armaments": "军需造船会社：章程有效（期限详见国家修正）",
    }
    for index, line in enumerate(lines):
        stripped = line.lstrip()
        for key, value in replacements.items():
            if stripped.startswith(f"{key}:0 "):
                lines[index] = f' {key}:0 "{value}"'
                break

    lines.extend(
        [
            ' jxp_a_socioeconomic_integration.estate.nobles:0 "武家奉公众：已列入当前国体"',
            ' jxp_a_socioeconomic_integration.estate.church:0 "寺社宗门：已列入当前国体"',
            ' jxp_a_socioeconomic_integration.estate.burghers:0 "町众豪商：已列入当前国体"',
            ' jxp_a_socioeconomic_integration.estate.communes:0 "百姓惣村：已列入当前国体"',
            ' jxp_a_socioeconomic_integration.estate.unready:0 "四阶层整编尚未完成，中央将在下一次有界校准时重试"',
            ' jxp_a_socioeconomic_integration.company.mining.nationalized:0 "金银山会所：已收归公仪，国营章程长期有效"',
            ' jxp_a_socioeconomic_integration.company.shipping.nationalized:0 "全国廻船会所：已收归公仪，国营章程长期有效"',
            ' jxp_a_socioeconomic_integration.company.rice.nationalized:0 "米市信用会所：已收归公仪，国营章程长期有效"',
            ' jxp_a_socioeconomic_integration.company.textile.nationalized:0 "织造会社：已收归公仪，国营章程长期有效"',
            ' jxp_a_socioeconomic_integration.company.armaments.nationalized:0 "军需造船会社：已收归公仪，国营章程长期有效"',
            ' jxp_a_socioeconomic_integration.company.state.expanding:0 "经营簿：至少一社会社正在扩张"',
            ' jxp_a_socioeconomic_integration.company.state.stable:0 "经营簿：至少一社会社经营稳健"',
            ' jxp_a_socioeconomic_integration.company.state.distressed:0 "经营簿：至少一社会社陷入困顿"',
            ' jxp_a_socioeconomic_integration.company.state.reformed:0 "经营簿：至少一社会社已经改组"',
            ' jxp_a_socioeconomic_integration.company.directors:0 "翻阅董事席与阶层权衡"',
            ' jxp_a_socioeconomic_integration.company.overseas:0 "翻阅送往海外经略册的会社请求"',
            ' jxp_a_socioeconomic_integration.company.back:0 "返回会社章程簿"',
            ' jxp_a_socioeconomic_integration.105.t:0 "会社董事席"',
            ' jxp_a_socioeconomic_integration.105.d:0 "董事席不是虚衔。国家奉行重审计与官营，町众豪商重贸易与信用，武家奉公众重军需，寺社宗门重赈济与共同体，混合评议则以较小收益换取阶层均衡。下列条目显示当前至少一家会社采用的董事结构。"',
            ' jxp_a_socioeconomic_integration.106.t:0 "海外会社接口簿"',
            ' jxp_a_socioeconomic_integration.106.d:0 "国内会社无权自行取得海外领土；本册只显示已经递交给海外经略系统的请求。是否受理、成立何种殖民会社及其领土后果，均由海外经略册另行裁定。"',
            ' jxp_a_socioeconomic_integration.request.none:0 "尚未向海外经略册递交会社请求"',
            ' jxp_a_socioeconomic_integration.request.red_seal:0 "已请求：朱印海外商社"',
            ' jxp_a_socioeconomic_integration.request.pacific:0 "已请求：太平洋敕许会社"',
            ' jxp_a_socioeconomic_integration.request.southern:0 "已请求：南洋会社"',
            ' jxp_a_socioeconomic_integration.request.northern:0 "已请求：北洋会社"',
            ' jxp_a_socioeconomic_integration.request.continental:0 "已请求：大陆经略会社"',
            ' jxp_a_socioeconomic_integration.100.identity:0 "查阅国体、创始家与统一来路"',
            ' jxp_a_socioeconomic_integration.107.t:0 "国体图志：本国身份"',
            ' jxp_a_socioeconomic_integration.107.d:0 "本页逐项显示当前实际生效的国内国体，而非只凭国号猜测。路线既定后，其阶层配置、经济制度、专属危机与国内大成各有自己的清理和迁移规则；商议日本在完成分支裁决前先由共同商议国制承接一级改革，随后才分为幕府监督、町众共和国或会社帝国。"',
            ' jxp_a_socioeconomic_integration.identity.daimyo:0 "当前国体：大名／独立大名／幕府阶段"',
            ' jxp_a_socioeconomic_integration.identity.uncommitted:0 "当前国体：未定日本·诸州公议"',
            ' jxp_a_socioeconomic_integration.identity.sakoku:0 "当前国体：锁国幕藩国家"',
            ' jxp_a_socioeconomic_integration.identity.open:0 "当前国体：开国海洋国家"',
            ' jxp_a_socioeconomic_integration.identity.buddhist:0 "当前国体：王法佛法之国"',
            ' jxp_a_socioeconomic_integration.identity.kirishitan:0 "当前国体：吉利支丹日本"',
            ' jxp_a_socioeconomic_integration.identity.confucian:0 "当前国体：儒教经世国家"',
            ' jxp_a_socioeconomic_integration.identity.imperial:0 "当前国体：皇政太政官国家"',
            ' jxp_a_socioeconomic_integration.identity.reformed:0 "当前国体：改革宗盟约国家"',
            ' jxp_a_socioeconomic_integration.identity.kaikyo:0 "当前国体：海商回教日本"',
            ' jxp_a_socioeconomic_integration.identity.ikko:0 "当前国体：一向净土国"',
            ' jxp_a_socioeconomic_integration.identity.wokou:0 "当前国体：倭寇海上联盟"',
            ' jxp_a_socioeconomic_integration.identity.toyotomi:0 "当前国体：丰臣关白·太阁政权"',
            ' jxp_a_socioeconomic_integration.identity.commercial:0 "当前国体：商议日本·天下会社国"',
            ' jxp_a_socioeconomic_integration.branch.foundation:0 "商议分支：共同商议国制（尚待最终裁决）"',
            ' jxp_a_socioeconomic_integration.branch.shogunate:0 "商议分支：幕府监督会社国"',
            ' jxp_a_socioeconomic_integration.branch.merchant:0 "商议分支：町众商议共和国"',
            ' jxp_a_socioeconomic_integration.branch.company:0 "商议分支：海外会社帝国"',
            ' jxp_a_socioeconomic_integration.identity.founder:0 "查阅创始家商业遗产"',
            ' jxp_a_socioeconomic_integration.identity.unification:0 "查阅天下一统的方法"',
            ' jxp_a_socioeconomic_integration.identity.era:0 "查阅三项时代属性与代价"',
            ' jxp_a_socioeconomic_integration.identity.back:0 "返回本国身份"',
            ' jxp_a_socioeconomic_integration.108.t:0 "创始家商业遗产"',
            ' jxp_a_socioeconomic_integration.108.d:0 "统一之家的旧政并不再叠加一套通用永久数值；它改为影响最适合的会社、董事、审计与国用选择。五类只会保留其一，改换国号或殖民继承时由中央重新核定。"',
            ' jxp_a_socioeconomic_integration.founder.commercial:0 "创始家遗产：城市与市场型"',
            ' jxp_a_socioeconomic_integration.founder.maritime:0 "创始家遗产：海商与港口型"',
            ' jxp_a_socioeconomic_integration.founder.bureaucratic:0 "创始家遗产：官僚与检地型"',
            ' jxp_a_socioeconomic_integration.founder.communal:0 "创始家遗产：共同体与寺社型"',
            ' jxp_a_socioeconomic_integration.founder.frontier:0 "创始家遗产：边疆与资源型"',
            ' jxp_a_socioeconomic_integration.109.t:0 "天下一统之法"',
            ' jxp_a_socioeconomic_integration.109.d:0 "军锋上洛、奉敕讨不庭与会盟诸侯分别改变武家处分、公共信用、国有化和地方票号的政治代价。中央只保留一种来路；旧版的三种建国修正会迁入本制并撤去，避免双重叠加。"',
            ' jxp_a_socioeconomic_integration.unification.blade:0 "一统方法：军锋上洛"',
            ' jxp_a_socioeconomic_integration.unification.edict:0 "一统方法：奉敕讨不庭"',
            ' jxp_a_socioeconomic_integration.unification.league:0 "一统方法：会盟诸侯"',
            ' jxp_a_socioeconomic_integration.unification.pending:0 "一统方法：尚在大名阶段，未作终局裁定"',
            ' jxp_a_socioeconomic_integration.110.t:0 "三项时代属性"',
            ' jxp_a_socioeconomic_integration.110.d:0 "天下秩序、朝廷名分与海门外学共同支撑商业化门槛。极高或极低都会带来一利一弊的动态国势；本页只读显示当前区间，不另加永久修正，也不会因打开图志改变属性。"',
            ' jxp_a_socioeconomic_integration.era.tenka.high:0 "天下秩序：高（征收稳健，地方弹性受限）"',
            ' jxp_a_socioeconomic_integration.era.tenka.middle:0 "天下秩序：中（尚无极端取舍）"',
            ' jxp_a_socioeconomic_integration.era.tenka.low:0 "天下秩序：低（地方灵活，信用风险上升）"',
            ' jxp_a_socioeconomic_integration.era.sanction.high:0 "朝廷名分：高（公债可信，政治交涉更繁）"',
            ' jxp_a_socioeconomic_integration.era.sanction.middle:0 "朝廷名分：中（尚无极端取舍）"',
            ' jxp_a_socioeconomic_integration.era.sanction.low:0 "朝廷名分：低（行事迅捷，合法性成本上升）"',
            ' jxp_a_socioeconomic_integration.era.ocean.high:0 "海门外学：高（技术流通，外来冲击加剧）"',
            ' jxp_a_socioeconomic_integration.era.ocean.middle:0 "海门外学：中（尚无极端取舍）"',
            ' jxp_a_socioeconomic_integration.era.ocean.low:0 "海门外学：低（内需安定，远洋经营迟缓）"',
        ]
    )
    lines.extend(
        f' {key}:0 "{label}"'
        for key, label in PLAYER_VISIBLE_STATE_LABELS.items()
    )
    return "\n".join(lines) + "\n"


def load_escape_text():
    path = REPO_ROOT / "skills/eu4-modding/scripts/escape_eu4_special_localisation.py"
    spec = importlib.util.spec_from_file_location("jxp_eu4_escape", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load localisation escaper: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.escape_text


def payloads() -> dict[Path, bytes]:
    source_loc = render_localisation()
    escape_text = load_escape_text()
    return {
        TRIGGER_PATH: render_triggers().encode("utf-8"),
        EFFECT_PATH: render_effects().encode("utf-8"),
        EVENT_PATH: render_events().encode("utf-8"),
        ON_ACTION_PATH: render_on_actions().encode("utf-8"),
        DECISION_PATH: render_decisions().encode("utf-8"),
        SOURCE_LOC_PATH: source_loc.encode("utf-8"),
        ACTIVE_LOC_PATH: escape_text(source_loc).encode("utf-8-sig"),
    }


def write_or_check(check: bool) -> int:
    stale: list[str] = []
    for relative, expected in payloads().items():
        target = MOD_ROOT / relative
        if check:
            if not target.is_file() or target.read_bytes() != expected:
                stale.append(relative.as_posix())
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(expected)
    if stale:
        for item in stale:
            print(f"stale: {item}", file=sys.stderr)
        return 1
    print("integration payload is current" if check else "integration payload generated")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return write_or_check(args.check)


if __name__ == "__main__":
    raise SystemExit(main())
